(function(global){
 'use strict';
 const dock={x:1510,y:3820};let game=null,state={phase:'idle',started:0,biteAt:0,hookAt:0,origin:null,target:null,hasPole:false,catches:0},panel=null,button=null,copy=null,action=null,lastDock=null;
 const clock=()=>performance.now();
 function atDock(p){return p.map==='town'&&p.x>=1440&&p.x<=1690&&p.y>=3650&&p.y<=4110;}
 function active(){return ['casting','waiting','bite','reeling','caught'].includes(state.phase);}
 function message(){const p=game?.pose();if(!state.hasPole)return 'Get a practice pole to try fishing. The preview is free.';if(!atDock(p||{}))return 'Walk to the southern pier, or use Go to dock.';return {idle:'Ready to cast. Watch for the bite, then tap Reel in!',casting:'Casting…',waiting:'Waiting for a bite…',bite:'BITE! Tap Reel in!',reeling:'Reeling in…',caught:'Caught a practice fish! No NFT was transferred.',missed:'It got away. Cast again!'}[state.phase]||'Ready to cast.';}
 function render(){if(!copy)return;copy.textContent=message();action.textContent=!state.hasPole?'Get practice pole · Free':state.phase==='bite'?'Reel in!':state.phase==='waiting'||state.phase==='casting'?'Waiting…':state.phase==='reeling'?'Reeling…':'Cast line';action.disabled=state.hasPole&&(!atDock(game.pose())||['casting','waiting','reeling'].includes(state.phase));panel.querySelector('[data-count]').textContent=`Practice catches: ${state.catches}`;button.textContent=state.phase==='bite'?'🎣 Reel!':state.phase==='casting'||state.phase==='waiting'?'🎣 Waiting':state.phase==='reeling'?'🎣 Reeling':state.phase==='caught'?'🎣 Caught!':'🎣';button.setAttribute('aria-label',state.phase==='bite'?'Reel in!':'Open fishing preview');}
 function phase(value,now=clock()){state.phase=value;state.started=now;game?.broadcast();render();}
 function stop(){if(state.phase!=='idle'){state.phase='idle';game?.broadcast();render();}}
 function cast(now=clock()){
  if(!game||!game.ready()||!state.hasPole||!atDock(game.pose())||['casting','waiting','bite','reeling'].includes(state.phase))return false;
  const p=game.pose();state.origin={x:p.x,y:p.y};state.target={x:p.x-205,y:p.y+45};state.biteAt=now+1800+Math.random()*2500;game.face('left');phase('casting',now);if(panel){panel.hidden=true;button.focus();}return true;
 }
 function reel(now=clock()){if(state.phase!=='bite')return false;state.hookAt=now;phase('reeling',now);return true;}
 function update(now){if(!game)return;const p=game.pose();if(button)button.hidden=!game.ready()&&panel.hidden;if(lastDock!==atDock(p)){lastDock=atDock(p);render();}if(active()&&(p.map!=='town'||!atDock(p)||Math.hypot(p.x-state.origin.x,p.y-state.origin.y)>9||p.airborne)){stop();return;}
  if(state.phase==='casting'&&now-state.started>=700)phase('waiting',now);
  if(state.phase==='waiting'&&now>=state.biteAt)phase('bite',now);
  else if(state.phase==='bite'&&now-state.started>2600)phase('missed',now);
  if(state.phase==='reeling'&&now-state.started>=1600){state.catches++;phase('caught',now);}
  if(state.phase==='caught'&&now-state.started>2200)phase('idle',now);
 }
 function publicState(){if(!active()||!state.origin)return null;return{phase:state.phase,x:state.origin.x,y:state.origin.y,targetX:state.target.x,targetY:state.target.y,character:game.pose().character||'classic',elapsed:Math.max(0,clock()-state.started)};}

 // ATM's left-facing forearm bends at the elbow; gloves share this frame layout.
 function armPose(s,age=0){if(!s||s.character!=='classic'||!['casting','waiting','bite','reeling','caught'].includes(s.phase))return null;const elapsed=Math.max(0,Number(s.elapsed||0)+age);const angle=1.35+(s.phase==='casting'?Math.sin(Math.min(1,elapsed/700)*Math.PI)*.30:s.phase==='reeling'?Math.sin(elapsed/95)*.10:0);return{angle,handX:(130-128-24*Math.sin(angle))*.33,handY:34+(216-303+24*Math.cos(angle))*.33};}
 function drawArmLayer(ctx,img,sx,sy,sw,sh,dx,dy,dw,dh,pose,gloves=false){const ax=112/256,ay=216/320,aw=42/256,ah=48/320;ctx.save();if(!gloves){ctx.beginPath();ctx.rect(dx,dy,dw,dh);ctx.rect(dx+ax*dw,dy+ay*dh,aw*dw,ah*dh);ctx.clip('evenodd');ctx.drawImage(img,sx,sy,sw,sh,dx,dy,dw,dh);ctx.restore();ctx.save();ctx.drawImage(img,sx+108/256*sw,sy+ay*sh,4/256*sw,ah*sh,dx+ax*dw,dy+ay*dh,aw*dw,ah*dh);}ctx.translate(dx+130/256*dw,dy+216/320*dh);ctx.rotate(pose.angle);ctx.drawImage(img,sx+ax*sw,sy+ay*sh,aw*sw,ah*sh,(112-130)/256*dw,0,aw*dw,ah*dh);ctx.restore();}
 function drawRig(ctx,s,now,age=0){if(!s||!Number.isFinite(s.x)||!Number.isFinite(s.y)||!Number.isFinite(s.targetX)||!Number.isFinite(s.targetY)||age>12000)return;const progress=Math.max(0,Math.min(1,(Number(s.elapsed||0)+age)/(s.phase==='reeling'?1600:700))),arm=armPose(s,age),hand={x:s.x+(arm?.handX??-14),y:s.y+(arm?.handY??-18)};let tip={x:hand.x-65,y:hand.y-57};if(s.phase==='casting'){tip={x:hand.x+Math.cos(-1.3-progress*1.1)*77,y:hand.y+Math.sin(-1.3-progress*1.1)*77};}
  let bob={x:s.targetX,y:s.targetY};if(s.phase==='casting'){bob={x:tip.x+(bob.x-tip.x)*progress,y:tip.y+(bob.y-tip.y)*progress-Math.sin(progress*Math.PI)*70};}if(s.phase==='reeling'||s.phase==='caught'){const t=s.phase==='caught'?1:progress;bob={x:s.targetX+(hand.x-s.targetX)*t,y:s.targetY+(hand.y-s.targetY)*t-Math.sin(t*Math.PI)*35};}
  ctx.save();ctx.lineCap='round';ctx.strokeStyle='#795025';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(hand.x,hand.y);ctx.quadraticCurveTo((hand.x+tip.x)/2,tip.y+15,tip.x,tip.y);ctx.stroke();ctx.strokeStyle='#efc57b';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#263e4c';ctx.fillRect(hand.x-6,hand.y-4,9,9);
  ctx.strokeStyle='rgba(235,250,255,.8)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(tip.x,tip.y);ctx.quadraticCurveTo((tip.x+bob.x)/2,Math.max(tip.y,bob.y)+14,bob.x,bob.y);ctx.stroke();
  const bobbing=Math.sin(now/220)*2*(s.phase==='bite'?3:1);if(['waiting','bite'].includes(s.phase)){for(let i=0;i<2;i++){const r=5+(now/65+i*10)%21;ctx.strokeStyle=`rgba(190,243,250,${(1-r/28)*.45})`;ctx.beginPath();ctx.ellipse(bob.x,bob.y+4,r,r*.35,0,0,Math.PI*2);ctx.stroke();}}
  if(['reeling','caught'].includes(s.phase)){ctx.fillStyle='#f3c953';ctx.beginPath();ctx.ellipse(bob.x,bob.y+7,10,5,-.3,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(bob.x+7,bob.y+6);ctx.lineTo(bob.x+16,bob.y+1);ctx.lineTo(bob.x+16,bob.y+13);ctx.closePath();ctx.fill();ctx.fillStyle='#183341';ctx.fillRect(bob.x-6,bob.y+5,2,2);}else{ctx.fillStyle='#f5f8ef';ctx.fillRect(bob.x-3,bob.y-5+bobbing,6,9);ctx.fillStyle='#ff655f';ctx.fillRect(bob.x-3,bob.y-5+bobbing,6,4);}
  if(s.phase==='bite'){ctx.font='900 14px system-ui';ctx.textAlign='center';ctx.fillStyle='#ffd45b';ctx.fillText('BITE!',s.x,s.y-88);}ctx.restore();
 }
 function draw(ctx,now,view,remotes){const inView=s=>s&&Math.max(s.x,s.targetX)+80>=view.x&&Math.min(s.x,s.targetX)-80<=view.x+view.w&&Math.max(s.y,s.targetY)+40>=view.y&&Math.min(s.y,s.targetY)-100<=view.y+view.h;if(inView(publicState()))drawRig(ctx,publicState(),now);for(const p of remotes||[]){if(p.map!=='town'||p.afk||p.powers?.invisibility)continue;const s=p.fishing;if(inView(s))drawRig(ctx,s,now,Math.max(0,Date.now()-p.lastSeen));}}
 function open(){if(!game?.ready())return;panel.hidden=false;render();panel.querySelector('[data-close]').focus();}
 function init(adapter){game=adapter;const style=document.createElement('style');style.textContent=`#atmFishingButton{position:fixed;right:12px;top:285px;z-index:32;min-width:46px;height:46px;border:1px solid #5bcbbb;border-radius:12px;background:#0b2634;color:#eaffff;font-size:18px;padding:0 10px;max-width:145px;cursor:pointer}#atmFishingPanel{position:fixed;right:12px;bottom:max(130px,20vh);width:min(310px,calc(100vw - 24px));z-index:80;padding:16px;border:1px solid #67dcc4;border-radius:18px;background:rgba(8,27,39,.97);color:#eaffff;box-shadow:0 8px 40px #0008;font:14px system-ui}#atmFishingPanel[hidden]{display:none}#atmFishingPanel h3{margin:0 30px 8px 0}#atmFishingPanel p{line-height:1.45;margin:8px 0}#atmFishingPanel button{min-height:44px;border:1px solid #5daaa2;border-radius:10px;background:#143d47;color:#f0fffb;padding:8px 12px;font-weight:800;cursor:pointer}#atmFishingPanel button:disabled{opacity:.55}#atmFishingPanel [data-cast]{display:block;width:100%;background:#5ce6c4;color:#092a25;font-size:16px;margin:12px 0}#atmFishingPanel [data-close]{position:absolute;right:10px;top:8px;min-width:36px;padding:4px}#atmFishingPanel small{color:#a4c6d0}body.atm-keyboard-open #atmFishingButton{display:none}@media(max-height:520px){#atmFishingButton{top:200px;right:70px}#atmFishingPanel{bottom:8px;max-height:calc(100dvh - 24px);overflow:auto}}`;document.head.appendChild(style);
  button=document.createElement('button');button.id='atmFishingButton';button.type='button';button.textContent='🎣';button.setAttribute('aria-label','Open fishing preview');button.onclick=()=>{if(state.phase==='bite')reel();else if(state.hasPole&&atDock(game.pose())&&!active())cast();else if(!active())open();};document.body.appendChild(button);
  panel=document.createElement('section');panel.id='atmFishingPanel';panel.hidden=true;panel.setAttribute('aria-label','Fishing preview');panel.innerHTML='<button type="button" data-close aria-label="Close fishing panel">×</button><h3>🎣 Fishing preview</h3><small>Southern pier · practice mode</small><p data-copy aria-live="polite"></p><button type="button" data-cast></button><button type="button" data-dock>Go to dock</button> <button type="button" data-stop>Stop fishing</button><p data-count></p><small>Practice fish only. NFT rewards and paid poles are not enabled yet.</small>';document.body.appendChild(panel);copy=panel.querySelector('[data-copy]');action=panel.querySelector('[data-cast]');action.onclick=()=>{if(!state.hasPole){state.hasPole=true;render();}else if(state.phase==='bite')reel();else cast();};panel.querySelector('[data-close]').onclick=()=>{panel.hidden=true;button.focus();};panel.querySelector('[data-stop]').onclick=stop;panel.querySelector('[data-dock]').onclick=async()=>{stop();action.disabled=true;try{await game.travel(dock);render();}catch(e){copy.textContent=e.message||'Could not load the pier. Walk south to reach it.';}};document.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea,select')||e.target?.isContentEditable)return;if(e.key==='Escape'){stop();panel.hidden=true;}if(e.code==='Space'&&state.phase==='bite'){e.preventDefault();reel();}});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});render();
 }
 global.ATMFishing=Object.freeze({init,update,draw,publicState,active,open,cast,reel,stop,atDock,armPose,drawArmLayer,drawHeldRod:(ctx,s)=>drawRig(ctx,s,clock())});
})(window);
