import {footprintContains} from './footprint-geometry.js';import {splitObjectPixels} from './object-silhouette.js';
(function(global){
 'use strict';let objects=[],lastRefresh=0,busy=false;const images=new Map(),layers=new Map();let mapPieceCache=new WeakMap();
 async function refresh(){if(busy||Date.now()-lastRefresh<60000)return;busy=true;lastRefresh=Date.now();try{const r=await fetch('/api/leaderboards?action=rewards-world-objects',{cache:'no-store'});if(!r.ok)throw Error('Objects unavailable');objects=(await r.json()).objects||[];mapPieceCache=new WeakMap();const urls=new Set(objects.map(o=>o.sprite_url));for(const [url] of images)if(!urls.has(url)){images.delete(url);layers.delete(url);}}catch(error){lastRefresh=Date.now()-50000;console.warn('Town objects:',error.message);}finally{busy=false;}}
 function zoneContains(o,key,x,y){const mask=o.collision?.masks?.[key];return !!mask&&footprintContains({...o,collision:mask},x,y);}
 function stairs(x,y){return objects.some(o=>o.active!==false&&(zoneContains(o,"stairs",x,y)||(o.collision?.cutouts||[]).some(r=>x-o.x>=r[0]&&x-o.x<=r[0]+r[2]&&y-o.y>=r[1]&&y-o.y<=r[1]+r[3])));}
 function interaction(x,y){const o=objects.find(o=>o.active!==false&&zoneContains(o,"action",x,y));return o?{id:o.id,type:"world-action",name:o.name,x,y,action:o.collision.action}:null;}
 function actors(view,foreground=[]){refresh();return objects.filter(o=>{const h=o.width*o.image_height/o.image_width;return o.x+o.width/2>=view.x&&o.x-o.width/2<=view.x+view.w&&o.y>=view.y&&o.y-h<=view.y+view.h;}).flatMap(o=>{const actor={depth:foreground.reduce((depth,p)=>o.x>=p.x&&o.x<=p.x+p.w&&o.y>=p.y&&o.y<=p.y+p.h?Math.max(depth,p.depth+.1):depth,o.y),type:'worldobject',object:o};if(o.collision?.depthMode==='silhouette')return [{...actor,depth:-Infinity,object:{...o,_silhouettePass:'shade'}},{...actor,depth:o.y+o.collision.depthLine-14,object:{...o,_silhouettePass:'body'}}];return o.collision?.masks?.depth?[{...actor,object:{...o,_depthPass:'base'}},{...actor,depth:Math.max(actor.depth,o.y+o.collision.depthLine),object:{...o,_depthPass:'mask'}}]:[actor];});}
 function objectImage(o){let img=images.get(o.sprite_url);if(!img){img=new Image();img.decoding='async';img.crossOrigin='anonymous';img.src=o.sprite_url;images.set(o.sprite_url,img);}return img;}
 function objectLayers(o,img){let parts=layers.get(o.sprite_url);if(parts)return parts;try{const off=document.createElement('canvas');off.width=img.naturalWidth;off.height=img.naturalHeight;const c=off.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0);const pixels=c.getImageData(0,0,off.width,off.height),split=splitObjectPixels(pixels.data);parts={};for(const key of ['body','shade','cover']){const layer=document.createElement('canvas');layer.width=off.width;layer.height=off.height;const painter=layer.getContext('2d');const data=painter.createImageData(off.width,off.height);data.data.set(split[key==='cover'?'body':key]);if(key==='cover')for(let i=3;i<data.data.length;i+=4)if(data.data[i])data.data[i]=255;painter.putImageData(data,0,0);parts[key]=layer;}}catch(error){console.warn('Object silhouette unavailable:',error.message);parts={body:img,shade:null,cover:null};}layers.set(o.sprite_url,parts);return parts;}
 function drawMapPiece(ctx,img,piece){
  const overlaps=objects.filter(o=>{const h=o.width*o.image_height/o.image_width;return o.active!==false&&o.x+o.width/2>piece.x&&o.x-o.width/2<piece.x+piece.w&&o.y>piece.y&&o.y-h<piece.y+piece.h;});
  if(!overlaps.length){ctx.drawImage(img,piece.x,piece.y,piece.w,piece.h);return;}
  let clipped=mapPieceCache.get(img);if(!clipped){const off=document.createElement('canvas');off.width=img.naturalWidth;off.height=img.naturalHeight;const painter=off.getContext('2d');painter.drawImage(img,0,0);painter.globalCompositeOperation='destination-out';let ready=true;for(const o of overlaps){const sprite=objectImage(o);if(!sprite.complete||!sprite.naturalWidth){ready=false;continue;}const cover=objectLayers(o,sprite).cover;if(!cover)continue;const h=o.width*o.image_height/o.image_width;painter.drawImage(cover,(o.x-o.width/2-piece.x)*off.width/piece.w,(o.y-h-piece.y)*off.height/piece.h,o.width*off.width/piece.w,h*off.height/piece.h);}clipped=off;if(ready)mapPieceCache.set(img,off);}
  ctx.drawImage(clipped,piece.x,piece.y,piece.w,piece.h);
 }
 function draw(ctx,o){const img=objectImage(o);if(!img.complete||!img.naturalWidth)return;const h=o.width*o.image_height/o.image_width;if(o._silhouettePass){const layer=objectLayers(o,img)[o._silhouettePass];if(layer)ctx.drawImage(layer,o.x-o.width/2,o.y-h,o.width,h);return;}if(o._depthPass){ctx.save();ctx.beginPath();if(o._depthPass==='base')ctx.rect(o.x-o.width/2,o.y-h,o.width,h);const c=o.collision.masks.depth;const vertices=c.type==='polygon'?c.points:[{x:c.offsetX-c.width/2,y:c.offsetY-c.depth/2},{x:c.offsetX+c.width/2,y:c.offsetY-c.depth/2},{x:c.offsetX+c.width/2,y:c.offsetY+c.depth/2},{x:c.offsetX-c.width/2,y:c.offsetY+c.depth/2}];vertices.forEach((v,i)=>ctx[i?'lineTo':'moveTo'](o.x+v.x,o.y+v.y));ctx.closePath();ctx.clip('evenodd');}ctx.drawImage(img,o.x-o.width/2,o.y-h,o.width,h);if(o._depthPass)ctx.restore();}
 function blocked(x,y){return objects.some(o=>o.solid&&o.active!==false&&footprintContains(o,x,y));}
 global.ATMWorldObjects=Object.freeze({actors,draw,drawMapPiece,blocked,refresh,stairs,interaction});
})(window);
