import {footprintContains} from './footprint-geometry.js';import {splitObjectPixels} from './object-silhouette.js';
(function(global){
 'use strict';let objects=[],lastRefresh=0,busy=false;const images=new Map(),layers=new Map();
 async function refresh(){if(busy||Date.now()-lastRefresh<60000)return;busy=true;lastRefresh=Date.now();try{const r=await fetch('/api/leaderboards?action=rewards-world-objects',{cache:'no-store'});if(!r.ok)throw Error('Objects unavailable');objects=(await r.json()).objects||[];const urls=new Set(objects.map(o=>o.sprite_url));for(const [url] of images)if(!urls.has(url)){images.delete(url);layers.delete(url);}}catch(error){lastRefresh=Date.now()-50000;console.warn('Town objects:',error.message);}finally{busy=false;}}
 function zoneContains(o,key,x,y){const mask=o.collision?.masks?.[key];return !!mask&&footprintContains({...o,collision:mask},x,y);}
 function stairs(x,y){return objects.some(o=>o.active!==false&&zoneContains(o,"stairs",x,y));}
 function interaction(x,y){const o=objects.find(o=>o.active!==false&&zoneContains(o,"action",x,y));return o?{id:o.id,type:"world-action",name:o.name,x,y,action:o.collision.action}:null;}
 function actors(view,foreground=[]){refresh();return objects.filter(o=>{const h=o.width*o.image_height/o.image_width;return o.x+o.width/2>=view.x&&o.x-o.width/2<=view.x+view.w&&o.y>=view.y&&o.y-h<=view.y+view.h;}).flatMap(o=>{const actor={depth:foreground.reduce((depth,p)=>o.x>=p.x&&o.x<=p.x+p.w&&o.y>=p.y&&o.y<=p.y+p.h?Math.max(depth,p.depth+.1):depth,o.y),type:'worldobject',object:o};if(o.collision?.depthMode==='silhouette')return [{...actor,depth:-Infinity,object:{...o,_silhouettePass:'shade'}},{...actor,depth:o.y+o.collision.depthLine-14,object:{...o,_silhouettePass:'body'}}];return o.collision?.masks?.depth?[{...actor,object:{...o,_depthPass:'base'}},{...actor,depth:Math.max(actor.depth,o.y+o.collision.depthLine),object:{...o,_depthPass:'mask'}}]:[actor];});}
 function draw(ctx,o){let img=images.get(o.sprite_url);if(!img){img=new Image();img.decoding='async';img.crossOrigin='anonymous';img.src=o.sprite_url;images.set(o.sprite_url,img);}if(img.complete&&img.naturalWidth){const h=o.width*o.image_height/o.image_width;if(o._silhouettePass){let parts=layers.get(o.sprite_url);if(!parts){try{const off=document.createElement('canvas');off.width=img.naturalWidth;off.height=img.naturalHeight;const c=off.getContext('2d',{willReadFrequently:true});c.drawImage(img,0,0);const pixels=c.getImageData(0,0,off.width,off.height),split=splitObjectPixels(pixels.data);parts={};for(const key of ['body','shade']){const layer=document.createElement('canvas');layer.width=off.width;layer.height=off.height;const painter=layer.getContext('2d');const data=painter.createImageData(off.width,off.height);data.data.set(split[key]);painter.putImageData(data,0,0);parts[key]=layer;}}catch(error){console.warn('Object silhouette unavailable:',error.message);parts={body:img,shade:null};}layers.set(o.sprite_url,parts);}const layer=parts[o._silhouettePass];if(layer)ctx.drawImage(layer,o.x-o.width/2,o.y-h,o.width,h);return;}if(o._depthPass){ctx.save();ctx.beginPath();if(o._depthPass==='base')ctx.rect(o.x-o.width/2,o.y-h,o.width,h);const c=o.collision.masks.depth;const vertices=c.type==='polygon'?c.points:[{x:c.offsetX-c.width/2,y:c.offsetY-c.depth/2},{x:c.offsetX+c.width/2,y:c.offsetY-c.depth/2},{x:c.offsetX+c.width/2,y:c.offsetY+c.depth/2},{x:c.offsetX-c.width/2,y:c.offsetY+c.depth/2}];vertices.forEach((v,i)=>ctx[i?'lineTo':'moveTo'](o.x+v.x,o.y+v.y));ctx.closePath();ctx.clip('evenodd');}ctx.drawImage(img,o.x-o.width/2,o.y-h,o.width,h);if(o._depthPass)ctx.restore();}}
 function blocked(x,y){return objects.some(o=>o.solid&&o.active!==false&&footprintContains(o,x,y));}
 global.ATMWorldObjects=Object.freeze({actors,draw,blocked,refresh,stairs,interaction});
})(window);
