import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {deflateSync} from 'node:zlib';
import {inspectSpritePng,normalizeEffects,attributePatch,mergedAttributeCatalog} from '../lib/attribute-catalog.js';
import {loadStorePrices,priceCart} from '../lib/attribute-store.js';
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
function chunk(type,data){const out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);out.write(type,4);data.copy(out,8);out.writeUInt32BE(crc32(out.subarray(4,-4)),out.length-4);return out;}
function png({width=768,height=1280,opaque=false}={}){const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const pixels=Buffer.alloc((width*4+1)*height);if(opaque)for(let y=0;y<height;y++)for(let x=0;x<width;x++)pixels[y*(width*4+1)+1+x*4+3]=255;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
const user={id:'00000000-0000-4000-8000-000000000001'},path=`${user.id}/11111111-1111-4111-8111-111111111111.png`;
function db({definition=null,definitions=[],prices=[],image=png()}={}){return {from(table){const query={select(){return this;},eq(){return this;},in(){return this;},maybeSingle:async()=>({data:definition,error:null}),then(resolve){return Promise.resolve({data:table==='attribute_definitions'?definitions:prices,error:null}).then(resolve);}};return query;},storage:{from(){return {download:async()=>({data:new Blob([image]),error:null})};}}};}
test('sprite publication accepts the standard transparent sheet and rejects malformed, opaque or wrongly sized images',()=>{assert.deepEqual(inspectSpritePng(png()),{width:768,height:1280});assert.throws(()=>inspectSpritePng(png({width:300})),/768/);assert.throws(()=>inspectSpritePng(png({opaque:true})),/transparent/);const damaged=png();damaged[damaged.length-15]^=1;assert.throws(()=>inspectSpritePng(damaged),/damaged|incomplete/);assert.throws(()=>inspectSpritePng(Buffer.from('<svg/>')),/PNG/);});
test('effects reject invalid and excessive values without accepting numeric strings',()=>{assert.deepEqual(normalizeEffects({speed:1.6,gravity:.4,jump:2}),{speed:1.6,gravity:.4,jump:2});for(const effect of [{speed:Infinity},{speed:'2'},{gravity:0},{jump:9},{speed:null}]){if(effect.speed===null)assert.deepEqual(normalizeEffects(effect),{speed:1,gravity:1,jump:1});else assert.throws(()=>normalizeEffects(effect));}});
test('new attributes validate character, category, image ownership and saved identity',async()=>{const input={name:'Fast Fuzzy Shoes',character_id:'fuzzy',category:'shoes',sprite_path:path,effects:{speed:1.8,gravity:.5,jump:2}};const saved=await attributePatch(db(),user,input);assert.match(saved.item_id,/^shoes:custom-/);assert.equal(saved.slot,'feet');assert.equal(saved.character_id,'fuzzy');assert.equal(saved.sprite_path,path);for(const patch of [{character_id:'made-up'},{category:'constructor'},{name:'<img src=x>'},{sprite_path:`another-user/11111111-1111-4111-8111-111111111111.png`},{sprite_path:null}])await assert.rejects(attributePatch(db(),user,{...input,...patch}));});
test('edits retain purchased item identity and character while updating effects',async()=>{const definition={item_id:'shoes:custom-test',character_id:'fuzzy',category:'shoes',sprite_path:path};const input={item_id:definition.item_id,name:'Fuzzy Shoes',character_id:'fuzzy',category:'shoes',effects:{speed:2}};const saved=await attributePatch(db({definition}),user,input);assert.equal(saved.item_id,definition.item_id);assert.equal(saved.sprite_path,path);assert.equal(saved.effects.speed,2);await assert.rejects(attributePatch(db({definition}),user,{...input,character_id:'classic'}),/keeps/);});
test('new items use authoritative prices, disabled sale and unsupported IDs stay unavailable',async()=>{const definitions=[{item_id:'shoes:custom-test'}],prices=[{item_id:'shoes:custom-test',active:true,xrp_amount:'4.5',atm_amount:'100'}];const admin=db({definitions,prices});assert.equal((await loadStorePrices(admin))['shoes:custom-test'].xrp,'4.5');assert.equal((await priceCart(admin,['shoes:custom-test'],'xrp')).total,'4.5');await assert.rejects(priceCart(admin,['shoes:made-up'],'xrp'),/not currently/);await assert.rejects(priceCart(db({definitions,prices:[{...prices[0],active:false}]}),['shoes:custom-test'],'xrp'),/not currently/);});
test('admin catalog preserves static defaults and adds project-specific uploaded attributes',()=>{const catalog=mergedAttributeCatalog([{item_id:'shoes:custom-test',name:'Fuzzy Shoes',character_id:'fuzzy',category:'shoes',slot:'feet',effects:{speed:2,gravity:1,jump:1}}]);assert.equal(catalog.items.find(item=>item.id==='shoes:lightning-force-ones').effects.speed,1.6);assert.deepEqual(catalog.items.find(item=>item.id==='shoes:custom-test').characterIds,['fuzzy']);});
const effectsContext={};vm.createContext(effectsContext);vm.runInContext(fs.readFileSync('js/attribute-effects.js','utf8'),effectsContext);
test('equipped effects stack within limits and gravity changes airtime without changing selected height',()=>{const effects=effectsContext.ATMAttributeEffects;assert.equal(effects.combine([{speed:2},{speed:2}]).speed,3);assert.equal(effects.combine([{jump:4},{jump:4}]).jump,8);const normal=effects.jumpProfile(effects.combine([])),low=effects.jumpProfile(effects.combine([{gravity:.25}]));assert.equal(low.height,normal.height);assert.equal(low.duration,normal.duration*2);});
const source=fs.readFileSync('js/runtime/game-core.js','utf8');
function runtimeContext(){const context={window:{atmActiveLoadout:{}},selectedCharacter:'fuzzy',ALLOWED_CHARACTERS:['classic','fuzzy'],ATM_ITEM_CATALOG:[],baseAttributeItems:[],attributeEffectOverrides:new Map(),ATM_EQUIPMENT_SHEETS:{},equipmentSheetImgs:{},Image:class {set src(value){this._src=value;}get src(){return this._src;}},URL,lockerOwnershipInfo:item=>({owned:item.owned===true}),lockerItemCompatibleWithCharacter:(item,character='fuzzy')=>item.compatibleCharacterIds.includes(character)};context.window.ATMAttributeEffects=effectsContext.ATMAttributeEffects;vm.createContext(context);const start=source.indexOf('function applyPublishedAttributes('),end=source.indexOf('let attributeCommerceRefreshPromise=',start);vm.runInContext(source.slice(start,end),context);return context;}
test('published catalog registers exact sprite/token-free ownership metadata and refreshed movement on the same item',()=>{const context=runtimeContext();const row={item_id:'shoes:custom-test',name:'Fuzzy Shoes',character_id:'fuzzy',slot:'feet',sprite_url:`https://xnyjurertwohlqczaeux.supabase.co/storage/v1/object/public/attribute-sprites/${path}`,effects:{speed:1.8}};context.applyPublishedAttributes([row]);assert.equal(context.ATM_ITEM_CATALOG[0].ownership,'store');assert.equal(context.ATM_ITEM_CATALOG[0].compatibleCharacterIds[0],'fuzzy');assert.equal(context.equipmentSheetImgs[row.item_id].src,row.sprite_url);context.applyPublishedAttributes([{...row,effects:{speed:2.2}}]);assert.equal(context.ATM_ITEM_CATALOG.length,1);assert.equal(context.attributeEffectOverrides.get(row.item_id).speed,2.2);context.applyPublishedAttributes([{...row,sprite_url:'https://evil.example/sheet.png'}]);assert.equal(context.ATM_ITEM_CATALOG.length,0);});
test('movement ignores unowned and incompatible equipped attributes',()=>{const context=runtimeContext();context.ATM_ITEM_CATALOG=[{id:'shoes:custom-test',type:'equipment',compatibleCharacterIds:['fuzzy'],owned:false},{id:'head:test',type:'equipment',compatibleCharacterIds:['classic'],owned:true}];context.window.atmActiveLoadout={feet:'shoes:custom-test',head:'head:test'};context.attributeEffectOverrides.set('shoes:custom-test',{speed:2});context.attributeEffectOverrides.set('head:test',{speed:2});const start=source.indexOf('function equippedAttributeEffects()'),end=source.indexOf('function playerMovementSpeedMultiplier()',start);vm.runInContext(source.slice(start,end),context);assert.equal(context.equippedAttributeEffects().speed,1);context.ATM_ITEM_CATALOG[0].owned=true;assert.equal(context.equippedAttributeEffects().speed,2);});
