import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
class Element {
 constructor(tag){this.tagName=tag;this.children=[];this.events={};this.files=[];this.attributes={};this._value='';this.disabled=false;this.classList={add(){},remove(){}};}
 set textContent(value){this.text=String(value);this.children=[];}get textContent(){return (this.text||'')+this.children.map(child=>child.textContent||'').join('');}
 set value(v){this._value=String(v);if(this.tagName==='input'&&this.type==='file'&&v==='')this.files=[];}get value(){return this._value;}
 append(...children){for(const child of children){child.parent=this;this.children.push(child);if(this.tagName==='select'&&!this.value)this.value=child.value;}}
 replaceChildren(...children){this.children=[];this.value='';this.append(...children);}setAttribute(key,value){this.attributes[key]=value;}addEventListener(type,fn){this.events[type]=fn;}dispatchEvent(event){return this.events[event.type]?.(event);}scrollIntoView(){}setPointerCapture(){}
 getContext(){return {getImageData:()=>({data:new Uint8Array([0,0,0,0])}),drawImage(){}};}
}
const all=root=>[root,...root.children.flatMap(all)];const event=type=>({type,preventDefault(){}});
function fixture(){const host=new Element('div'),calls=[],uploads=[];const context={document:{createElement:tag=>new Element(tag),hidden:false},window:{addEventListener(){}},Event:class{constructor(type){this.type=type;}},Image:class{constructor(){this.complete=true;this.naturalWidth=768;this.naturalHeight=1280;}set src(value){this._src=value;queueMicrotask(()=>this.onload?.());}},URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},requestAnimationFrame(){},console};vm.createContext(context);vm.runInContext(fs.readFileSync('js/attribute-effects.js','utf8'),context);vm.runInContext(fs.readFileSync('admin/attribute-editor.js','utf8').replace("import '../js/attribute-effects.js';",'').replace('export function mountAttributeEditor','function mountAttributeEditor'),context);
 const editor=context.mountAttributeEditor({host,client:{storage:{from(){return {getPublicUrl:path=>({data:{publicUrl:'https://storage/'+path}}),uploadToSignedUrl:async(...args)=>{uploads.push(args);return {error:null};}};}}},api:async(action,body)=>{calls.push({action,body});return action==='admin-attribute-upload'?{bucket:'attribute-sprites',path:'user/test.png',token:'signed-token'}:{saved:true,item_id:body.item_id||'shoes:custom-saved'};},getCatalog:()=>({characters:[{id:'classic',name:'ATM',sprite_src:'assets/characters/playable/atm.webp'},{id:'fuzzy',name:'Fuzzy'}]}),onSaved:async()=>{},status(){}});return {host,editor,calls,uploads};}
const input=(host,label)=>all(host).find(n=>n.tagName==='label'&&(n.text||'')===label)?.children.find(n=>['input','select'].includes(n.tagName));
test('existing attributes expose their saved movement, preserve disabled prices, and save without reuploading',async()=>{const {host,editor,calls,uploads}=fixture();editor.open({id:'shoes:lightning-force-ones',name:'Lightning Force Ones',characterIds:['classic'],category:'shoes',effects:{speed:1.6,gravity:1,jump:1},sprite_src:'shoe.png'},{xrp_amount:null,active:false});assert.equal(input(host,'XRP price').value,'');assert.equal(input(host,'Character').disabled,true);const slider=all(host).find(n=>n.attributes['aria-label']==='Movement speed');assert.equal(slider.value,'1.6');slider.value='2.1';slider.dispatchEvent(event('input'));await all(host).find(n=>n.tagName==='form').dispatchEvent(event('submit'));assert.equal(uploads.length,0);assert.equal(calls[0].action,'admin-attribute-save');assert.equal(calls[0].body.effects.speed,2.1);assert.equal(calls[0].body.xrp_amount,'');assert.equal(calls[0].body.active,false);});
test('new sprite upload uses the signed storage token and publishes the selected character, category and effects',async()=>{const {host,editor,calls,uploads}=fixture();editor.open();input(host,'Attribute name').value='Fuzzy Fast Shoes';input(host,'Character').value='fuzzy';input(host,'Category').value='shoes';const file=input(host,'Sprite sheet (transparent PNG)');file.files=[{type:'image/png',size:200}];await file.dispatchEvent(event('change'));await all(host).find(n=>n.tagName==='form').dispatchEvent(event('submit'));assert.equal(uploads.length,1);assert.equal(uploads[0][1],'signed-token');assert.equal(calls[1].body.sprite_path,'user/test.png');assert.equal(calls[1].body.character_id,'fuzzy');assert.equal(calls[1].body.category,'shoes');assert.equal(calls[1].body.effects.speed,1);await all(host).find(n=>n.tagName==='form').dispatchEvent(event('submit'));assert.equal(uploads.length,1);assert.equal(calls[2].body.item_id,'shoes:custom-saved');});
test('invalid dropped file cannot silently publish a previously selected sprite',async()=>{const {host,editor,calls}=fixture();editor.open({id:'shoes:existing',name:'Existing',characterIds:['classic'],category:'shoes'},{});const drop=all(host).find(n=>n.className==='sprite-drop');await drop.dispatchEvent({...event('drop'),dataTransfer:{files:[{type:'text/html',size:10}]}});await all(host).find(n=>n.tagName==='form').dispatchEvent(event('submit'));assert.equal(calls.length,0);});
