import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function playable(borrow=true){let now=0,pose={map:'town',x:1510,y:3820,airborne:false};const created=[];class E{hidden=true;children=new Map();setAttribute(){}appendChild(){}focus(){}querySelector(k){if(!this.children.has(k))this.children.set(k,new E());return this.children.get(k);}}const doc={head:new E(),body:new E(),createElement(){const el=new E();created.push(el);return el;},addEventListener(){}};const math=Object.create(Math);math.random=()=>0;const c=vm.createContext({window:{},document:doc,performance:{now:()=>now},Math:math,Date});vm.runInContext(fs.readFileSync(new URL('../js/fishing.js',import.meta.url),'utf8'),c);const f=c.window.ATMFishing;f.init({ready:()=>true,pose:()=>pose,face:()=>{},broadcast:()=>{},travel:async()=>{}});if(borrow)created.find(e=>e.id==='atmFishingPanel').querySelector('[data-cast]').onclick();return{f,pose,panel:created.find(e=>e.id==='atmFishingPanel'),button:created.find(e=>e.id==='atmFishingButton'),tick(t){now=t;f.update(t);}};}
test('cast, bite window, reel, catch and idle timings',()=>{const s=playable();assert.equal(s.f.cast(),true);assert.equal(s.f.publicState().phase,'casting');s.tick(710);assert.equal(s.f.publicState().phase,'waiting');s.tick(1810);assert.equal(s.f.publicState().phase,'bite');assert.equal(s.f.reel(),true);s.tick(3420);assert.equal(s.f.publicState().phase,'caught');s.tick(5700);assert.equal(s.f.publicState(),null);});
test('missing a bite gives no catch and moving/map changes cancel the cast',()=>{const s=playable();s.f.cast();s.tick(710);s.tick(1810);s.tick(4500);assert.equal(s.f.publicState(),null);assert.equal(s.f.reel(),false);s.f.cast();s.pose.x+=20;s.tick(4510);assert.equal(s.f.active(),false);s.pose.map='arcade';assert.equal(s.f.cast(),false);});
test('render uses a rod, line and bobber without issuing reward transactions',()=>{const s=playable();s.f.cast();s.tick(710);let strokes=0;const ctx=new Proxy({stroke(){strokes++;}},{get:(target,key)=>target[key]||(()=>{})});s.f.draw(ctx,710,{x:1100,y:3600,w:800,h:800},[]);assert.ok(strokes>=3);});

test('requires a practice pole before casting',()=>{const s=playable(false);assert.equal(s.f.cast(),false);assert.equal(s.f.active(),false);});

test('casting clears the panel and compact control reels and recasts',()=>{const s=playable();s.f.open();assert.equal(s.panel.hidden,false);s.panel.querySelector('[data-cast]').onclick();assert.equal(s.panel.hidden,true);s.tick(710);s.tick(1810);s.button.onclick();assert.equal(s.f.publicState().phase,'reeling');s.tick(3420);s.tick(5700);s.button.onclick();assert.equal(s.f.publicState().phase,'casting');assert.equal(s.panel.hidden,true);});

test('ATM grip follows the animated forearm while other characters keep their own pose',()=>{const s=playable();s.f.cast();const waiting=s.f.armPose({character:'classic',phase:'waiting',elapsed:0});assert.ok(waiting.handY>0);assert.ok(waiting.handX<0);const casting=s.f.armPose({character:'classic',phase:'casting',elapsed:350});assert.notEqual(casting.handX,waiting.handX);assert.equal(s.f.armPose({character:'fuzzy',phase:'waiting',elapsed:0}),null);assert.equal(s.f.armPose(null),null);let rotation=null;const ctx=new Proxy({rotate(a){rotation=a;}},{get:(t,k)=>t[k]||(()=>{})});s.f.drawArmLayer(ctx,{},256,320,256,320,0,0,84,106,waiting,true);assert.equal(rotation,waiting.angle);});
