import {test} from 'node:test';import assert from 'node:assert/strict';
import {fundingStep,remainingFunding} from '../admin/funding-step.js';
import {startFundingFlow} from '../admin/topup-flow.js';
const cycle={id:'cycle',status:'pending',fundingStage:'xrp',payoutBudget:'10000',payoutDepositRequired:'10200.00000000102',payoutReceived:'0',xrpFeeRequired:'0.01',xrpReceived:'0'};
test('fees and token deposit remain separate and show the exact remaining amounts',()=>{assert.equal(fundingStep(cycle,'666').label,'Fund fees: 0.01 XRP');assert.equal(fundingStep({...cycle,fundingStage:'payout',xrpReceived:'0.01'},'666').label,'Continue: send 10200.00000000102 666');assert.equal(remainingFunding('10200.00000000102','200'),'10000.00000000102');assert.equal(remainingFunding('0.01','0.003',6),'0.007');assert.throws(()=>remainingFunding('1e4'));assert.equal(fundingStep({...cycle,status:'active'},'666').ready,true);});
class Node {constructor(tag,text){this.tag=tag;this.textContent=text;this.children=[];this.isConnected=true;this.events={};}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}addEventListener(type,fn){this.events[type]=fn;}}
const node=(tag,text)=>new Node(tag,text);
test('fee request is reviewed before opening Xaman and confirmation exposes the token continuation',async()=>{
 const original=globalThis.setTimeout;globalThis.setTimeout=()=>0;const host=node('div'),button=node('button'),calls=[];let confirmed=0;
 const api=async(action,body)=>{calls.push(action);return action==='admin-wallet-topup'?{cycle,xamanRequest:{stage:'xrp',deeplink:'https://xumm.app/sign/fee'}}:{cycle:{...cycle,fundingStage:'payout',xrpReceived:'0.01'}};};
 try{await startFundingFlow({slug:'luci',amount:'10000',symbol:'666',button,host,api,node,status:()=>{},loadWallets:()=>confirmed++});
 assert.equal(host.children.find(n=>n.tag==='a').textContent,'Open Xaman: send 0.01 XRP');assert.match(host.children[0].textContent,/Step 1 of 2/);
 await host.children.find(n=>n.textContent==='Check funding status').events.click();assert.equal(host.children.some(n=>n.tag==='a'),false);assert.equal(host.children.find(n=>n.tag==='button').textContent,'Continue: send 10200.00000000102 666');assert.equal(confirmed,0);assert.deepEqual(calls,['admin-wallet-topup','admin-wallet-topup-status']);
 }finally{globalThis.setTimeout=original;host._stopFunding();}
});
test('a token request cannot silently open an XRP request',async()=>{const host=node('div'),button=node('button');await startFundingFlow({slug:'luci',amount:'10000',symbol:'666',button,host,node,status:()=>{},loadWallets:()=>{},api:async()=>({cycle:{...cycle,fundingStage:'payout'},xamanRequest:{stage:'xrp',deeplink:'https://xumm.app/sign/wrong'}})});assert.equal(host.children.some(n=>n.tag==='a'),false);assert.match(host.children[0].textContent,/Funding step changed/);});
test('token funding confirmation refreshes balances only when active',async()=>{const original=globalThis.setTimeout;globalThis.setTimeout=()=>0;const host=node('div'),button=node('button');let confirmed=0;try{await startFundingFlow({slug:'luci',amount:'10000',symbol:'666',button,host,node,status:()=>{},loadWallets:()=>confirmed++,api:async action=>action==='admin-wallet-topup'?{cycle:{...cycle,fundingStage:'payout'},xamanRequest:{stage:'token',deeplink:'https://xumm.app/sign/token'}}:{cycle:{...cycle,status:'active',fundingStage:'ready'}}});assert.equal(confirmed,0);await host.children.find(n=>n.textContent==='Check funding status').events.click();assert.equal(confirmed,1);assert.equal(button.textContent,'Top-up confirmed');}finally{globalThis.setTimeout=original;host._stopFunding();}});
