import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {luciEligibility} from '../lib/npc-security.js';
const now=Date.parse('2026-10-06T22:00:00Z'),user={id:'11111111-1111-4111-8111-111111111111',email_confirmed_at:'2026-10-01T00:00:00Z',created_at:'2026-10-01T00:00:00Z'},account={wallet_verified_at:'2026-10-01T00:00:00Z'};
test('Luci requires confirmed email, 24-hour account age and a one-hour verified wallet',()=>{assert.equal(luciEligibility(user,account,now).eligible,true);assert.equal(luciEligibility({...user,email_confirmed_at:null},account,now).eligible,false);assert.equal(luciEligibility({...user,created_at:new Date(now-23*3600000).toISOString()},account,now).eligible,false);assert.equal(luciEligibility(user,{wallet_verified_at:new Date(now-59*60000).toISOString()},now).eligible,false);assert.equal(luciEligibility({...user,created_at:'invalid'},account,now).eligible,false);assert.equal(luciEligibility(user,{},now).eligible,false);assert.equal(luciEligibility({...user,created_at:new Date(now-24*3600000).toISOString()},{wallet_verified_at:new Date(now-3600000).toISOString()},now).eligible,true);});
function fixture(authUser=user){const requests=[];const profile={wallet_address:'rGQjB1JL31cHKdEkz7LArEkVbTnjWJwvCk',...account};const query={select(){return this},eq(){return this},maybeSingle:async()=>({data:profile}),single:async()=>({data:profile})};const deps={luciEligibility,requireUser:async()=>({user:authUser,admin:{from:()=>query}}),npcProgram:()=>({id:'luci',slug:'luci-666-welcome'}),npcPath:()=>'/claim',payloadIntegrationRequest:async(path,body)=>{requests.push({path,body});return {status:'success'}},npcReceipt:result=>result,sendError:(res,error)=>res.status(error.status||500).json({error:error.message})};const source=readFileSync('lib/town-economy.js','utf8').replace(/^import .*$/mg,'').replace(/^export /mg,'');const handle=new Function(...Object.keys(deps),source+'\nreturn handleEconomy;')(...Object.values(deps));const res={code:200,status(code){this.code=code;return this},json(body){this.body=body;return this}};return {handle,res,requests};}
test('the signed NPC request uses the authenticated user ID and verified wallet, ignoring browser identity fields',async()=>{const f=fixture();await f.handle({method:'POST',body:{action:'rewards-npc-claim',npc_id:'luci',externalUserId:'attacker',walletAddress:'attacker',created_at:'2000-01-01'}},f.res);assert.equal(f.res.code,200);assert.equal(f.requests[0].body.externalUserId,user.id);assert.equal(f.requests[0].body.walletAddress,'rGQjB1JL31cHKdEkz7LArEkVbTnjWJwvCk');});
test('new accounts cannot bypass the age gate with browser-supplied timestamps',async()=>{const f=fixture({...user,created_at:new Date().toISOString()});await f.handle({method:'POST',body:{action:'rewards-npc-claim',npc_id:'luci',created_at:'2000-01-01'}},f.res);assert.equal(f.res.code,403);assert.equal(f.requests.length,0);assert.match(f.res.body.error,/24 hours/);});
test('status checks expose eligibility waits and carry authenticated identity for eligible players',async()=>{const young=fixture({...user,created_at:new Date().toISOString()});await young.handle({method:'GET',query:{action:'rewards-npc-status',npc_id:'luci'}},young.res);assert.equal(young.res.body.eligible,false);assert.equal(young.requests.length,0);const old=fixture();await old.handle({method:'GET',query:{action:'rewards-npc-status',npc_id:'luci'}},old.res);assert.match(old.requests[0].path,new RegExp('externalUserId='+user.id));});
function commerceFixture(authUser=user){const requests=[];const query={select(){return this},eq(){return this},single:async()=>({data:{wallet_address:'rGQjB1JL31cHKdEkz7LArEkVbTnjWJwvCk',...account}})};const deps={luciEligibility,requireUser:async()=>({user:authUser,admin:{from:()=>query}}),payloadIntegrationRequest:async(path,body)=>{requests.push({path,body});return {eligible:true,amount:'6'}}};const source=readFileSync('api/xaman-vending-start.js','utf8').replace(/^import[\s\S]*?;\n/mg,'').replace('export default async function','async function');const handlers=new Function(...Object.keys(deps),source+'\nreturn {handleLuci666RewardStatus,handleLuci666RewardClaim};')(...Object.values(deps));const res={status(){return this},json(body){this.body=body;return this}};return {...handlers,res,requests};}
test('the Luci commerce endpoint used in the game enforces the same age and identity checks',async()=>{const young=commerceFixture({...user,created_at:new Date().toISOString()});await young.handleLuci666RewardStatus({},young.res);assert.equal(young.res.body.eligible,false);assert.equal(young.requests.length,0);await assert.rejects(()=>young.handleLuci666RewardClaim({},young.res),/24 hours/);const old=commerceFixture();await old.handleLuci666RewardStatus({},old.res);assert.match(old.requests[0].path,new RegExp('externalUserId='+user.id));assert.equal(old.res.body.eligible,true);});
