import test from 'node:test';import assert from 'node:assert/strict';
import {exactToken,krakenXrpUsd,ammTokenUsd,tokenUsdPrice} from '../lib/token-usd-price.js';
import {usdAmount,tokenIdentity,attachUsdEstimate} from '../admin/usd-estimate.js';
const asset=exactToken({currency:'TRISK',issuer:'rhu8q21DEWekDcvqakABXPJbm3MAnQa8oy'});
const pool={validated:true,ledger_index:100,amm:{amount:'3000000000',amount2:{...asset,value:'10000000'}}};
test('project identity normalizes symbols to XRPL codes without confusing issuers',()=>{assert.equal(asset.currency,'545249534B000000000000000000000000000000');assert.equal(tokenIdentity({currency:'TRISK',issuer:asset.issuer}),tokenIdentity(asset));assert.notEqual(tokenIdentity({...asset,issuer:'another'}),tokenIdentity(asset));assert.throws(()=>exactToken({currency:'XRP',issuer:asset.issuer}));assert.throws(()=>exactToken({currency:'TRISK',issuer:'not-an-address'}));});
test('USD quote uses the exact XRPL pool reserves with correct XRP drops and asset ordering',()=>{assert.equal(ammTokenUsd(pool,asset,1.5).usd_per_token,.00045);assert.equal(ammTokenUsd({...pool,amm:{amount:pool.amm.amount2,amount2:pool.amm.amount}},asset,1.5).usd_per_token,.00045);assert.equal(ammTokenUsd(pool,asset,1.5).pool_liquidity_usd,9000);});
test('unvalidated, frozen, mismatched or thin pools never produce a price',()=>{for(const result of [{...pool,validated:false},{...pool,amm:{...pool.amm,asset2_frozen:true}},{...pool,amm:{...pool.amm,amount2:{...pool.amm.amount2,issuer:'wrong'}}},{...pool,amm:{...pool.amm,amount:'1000000'}},{...pool,amm:{...pool.amm,amount2:{...pool.amm.amount2,value:'0'}}}])assert.throws(()=>ammTokenUsd(result,asset,1.5));});
test('XRP/USD must come from the exact USD ticker with valid bid/ask prices',()=>{assert.equal(krakenXrpUsd({error:[],result:{XXRPZUSD:{b:['1.49'],a:['1.51']}}}),1.5);for(const payload of [{error:['failure']},{error:[],result:{XRPEUR:{b:['1'],a:['1']}}},{error:[],result:{XXRPZUSD:{b:['2'],a:['1']}}},{error:[],result:{XXRPZUSD:{b:['1'],a:['10']}}}])assert.throws(()=>krakenXrpUsd(payload));});
test('amount estimates update locally, preserve small values and refuse stale or absent prices',()=>{const quote={available:true,usd_per_token:.00045,expires_at:'2030-01-01T00:00:00Z'};assert.equal(usdAmount('10000',quote,0),'≈ $4.50 USD');assert.equal(usdAmount('20000',quote,0),'≈ $9.00 USD');assert.equal(usdAmount('1',quote,0),'≈ less than $0.01 USD');assert.equal(usdAmount('10000',{...quote,expires_at:'1970-01-01T00:00:00Z'},1),'USD estimate unavailable');assert.equal(usdAmount('10000',{available:false},0),'USD estimate unavailable');assert.match(usdAmount('-100',quote,0),/Enter/);});
test('requests are deduplicated and live prices are cached per exact token',async()=>{const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,options)=>{calls.push(url);return {ok:true,json:async()=>url.includes('kraken')?{error:[],result:{XXRPZUSD:{b:['1.5'],a:['1.5']}}}:{result:pool}};};try{const [first,second]=await Promise.all([tokenUsdPrice(asset),tokenUsdPrice(asset)]);assert.equal(first.available,true);assert.equal(first.usd_per_token,second.usd_per_token);assert.equal(calls.filter(url=>url.includes('kraken')).length,1);assert.equal(calls.length,4);await tokenUsdPrice(asset);assert.equal(calls.length,4);}finally{globalThis.fetch=original;}});
class Node{constructor(){this.children=[];this.events={};this.value='10000';this.isConnected=true;}append(...nodes){this.children.push(...nodes);}setAttribute(){}addEventListener(type,fn){this.events[type]=fn;}}
test('top-up estimator fetches on opening and updates while typing without changing the token amount',async()=>{const originalDocument=globalThis.document,originalSetInterval=globalThis.setInterval;globalThis.document={createElement:()=>new Node(),hidden:false};globalThis.setInterval=()=>0;const form=new Node(),input=new Node(),details={hidden:true,events:{},addEventListener(type,fn){this.events[type]=fn;}};let calls=0;try{const estimate=attachUsdEstimate({form,input,details,token:{...asset,issuer:'unique-test'},getPrice:async()=>{calls++;return {...asset,issuer:'unique-test',available:true,usd_per_token:.00045,checked_at:new Date().toISOString(),expires_at:new Date(Date.now()+60000).toISOString()};}});await estimate.refresh();assert.equal(calls,0);details.hidden=false;await estimate.refresh();assert.equal(form.children[0].children[0].textContent,'≈ $4.50 USD');input.value='20000';input.events.input();assert.equal(form.children[0].children[0].textContent,'≈ $9.00 USD');assert.equal(input.value,'20000');assert.equal(calls,1);}finally{globalThis.document=originalDocument;globalThis.setInterval=originalSetInterval;}});
