import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {deflateSync} from 'node:zlib';
import {inspectSpritePng} from '../lib/attribute-catalog.js';import {saveWorldObject} from '../lib/world-objects.js';
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(type,data){const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,-4)),b.length-4);return b;}
function png(w,h,{rgb=false,opaque=false}={}){const b=Buffer.alloc(13);b.writeUInt32BE(w);b.writeUInt32BE(h,4);b[8]=8;b[9]=rgb?2:6;const channels=rgb?3:4,pixels=Buffer.alloc((w*channels+1)*h);if(opaque&&!rgb)for(let y=0;y<h;y++)for(let x=0;x<w;x++)pixels[y*(w*4+1)+1+x*4+3]=255;return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',b),chunk('IDAT',deflateSync(pixels)),chunk('IEND',Buffer.alloc(0))]);}
test('object PNGs allow non-sprite dimensions with optional transparency and required integrity checks',()=>{assert.deepEqual(inspectSpritePng(png(64,100),{object:true}),{width:64,height:100});assert.throws(()=>inspectSpritePng(png(64,100)),/768/);assert.throws(()=>inspectSpritePng(png(2049,1),{object:true}),/2048/);const damaged=png(20,30);damaged[40]^=1;assert.throws(()=>inspectSpritePng(damaged,{object:true}),/damaged/);});
test('object saves reject invalid placement and cross-admin uploads before publication',async()=>{const user={id:'00000000-0000-4000-8000-000000000001'},valid={name:'NFT Donation Box',x:100,y:100,width:80,active:true,solid:false};await assert.rejects(saveWorldObject({},user,{...valid,x:-1}),/inside the map/);await assert.rejects(saveWorldObject({},user,{...valid,width:1000}),/512/);await assert.rejects(saveWorldObject({},user,{...valid,sprite_path:'another-admin/image.png'}),/this admin/);});
test('all players receive saved objects with bottom-center rendering, viewport culling and optional base collision',async()=>{const objects=[{id:'box',x:100,y:200,width:80,image_width:40,image_height:60,solid:true,sprite_url:'https://example/box.png'},{id:'far',x:3000,y:4000,width:80,image_width:40,image_height:60,solid:false,sprite_url:'https://example/far.png'}];class Image{complete=true;naturalWidth=40;naturalHeight=60;}
 const context=vm.createContext({window:{},fetch:async()=>({ok:true,json:async()=>({objects})}),Image,console,Date});vm.runInContext(fs.readFileSync(new URL('../js/world-objects.js',import.meta.url),'utf8'),context);const runtime=context.window.ATMWorldObjects;await runtime.refresh();const actors=runtime.actors({x:0,y:0,w:300,h:300});assert.equal(actors.length,1);assert.equal(actors[0].depth,200);const draws=[];runtime.draw({drawImage:(...args)=>draws.push(args)},objects[0]);assert.deepEqual(draws[0].slice(1),[60,80,80,120]);assert.equal(runtime.blocked(100,195),true);assert.equal(runtime.blocked(100,100),false);assert.equal(runtime.blocked(3000,3995),false);});

test('map objects accept opaque RGB and RGBA PNGs while sprite sheets still require transparency',()=>{for(const options of [{rgb:true},{opaque:true}]){const bytes=png(64,100,options);assert.deepEqual(inspectSpritePng(bytes,{object:true}),{width:64,height:100});}assert.throws(()=>inspectSpritePng(png(768,1280,{rgb:true})),/transparent/);assert.throws(()=>inspectSpritePng(png(768,1280,{opaque:true})),/transparent/);});

test('objects placed on foreground structures render above the supporting structure',async()=>{const object={x:1294.4,y:1655.1,width:100,image_width:1122,image_height:1402,sprite_url:'test'};const context=vm.createContext({window:{},fetch:async()=>({ok:true,json:async()=>({objects:[object]})}),console,Date});vm.runInContext(fs.readFileSync(new URL('../js/world-objects.js',import.meta.url),'utf8'),context);await context.window.ATMWorldObjects.refresh();const view={x:1000,y:1300,w:600,h:600};assert.equal(context.window.ATMWorldObjects.actors(view,[{x:436,y:1335,w:1010,h:363,depth:1697}])[0].depth,1697.1);assert.equal(context.window.ATMWorldObjects.actors(view,[{x:2000,y:1335,w:100,h:400,depth:1800}])[0].depth,object.y);});
