import { createHash } from 'node:crypto';
import { XAMAN_API_BASE, XAMAN_PAYLOAD_UUID, XRPL_TX_HASH, fetchXamanPayload, readJson, xamanHeaders, xamanError } from './xaman-vending.js';

export const ATTRIBUTE_STORE_DESTINATION = 'rMSDXpxDpV2pQJDHbp77XHHhT9QHMrfPYB';
export const ATTRIBUTE_STORE_ASSETS = Object.freeze({
  atm: Object.freeze({ id:'atm', label:'ATM', type:'issued', currency:'ATM', issuer:'raDZ4t8WPXkmDfJWMLBcNZmmSHmBC523NZ' }),
  rlusd: Object.freeze({ id:'rlusd', label:'RLUSD', type:'issued', currency:'524C555344000000000000000000000000000000', issuer:'rMxCKbEDwqr76QuheSUMdEGf4B9xJ8m5De' }),
  xrp: Object.freeze({ id:'xrp', label:'XRP', type:'native', currency:'XRP', issuer:null })
});
export const ATTRIBUTE_STORE_PAYMENT_WINDOW_MINUTES = 30;
const RIPPLE_EPOCH_OFFSET_SECONDS = 946684800;
const TF_PARTIAL_PAYMENT = 0x00020000;
const XRPL_ADDRESS = /^r[1-9A-HJ-NP-Za-km-z]{24,34}$/;

export function storeAsset(assetId){const asset=ATTRIBUTE_STORE_ASSETS[String(assetId||'').toLowerCase()];if(!asset)throw Object.assign(new Error('Choose ATM, RLUSD, or XRP.'),{status:400});return asset;}
export function normalizeItemIds(input){const ids=[...new Set((Array.isArray(input)?input:[]).map(v=>String(v||'').trim()).filter(Boolean))];if(!ids.length||ids.length>20)throw Object.assign(new Error('Choose between 1 and 20 attributes.'),{status:400});return ids;}
export function normalizeDecimal(value){const input=String(value??'').trim();if(!/^\d+(?:\.\d+)?$/.test(input))return null;let [whole,fraction='']=input.split('.');whole=whole.replace(/^0+(?=\d)/,'')||'0';fraction=fraction.replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole;}
function addDecimalStrings(values){const normalized=values.map(normalizeDecimal);if(normalized.some(value=>value===null))throw Object.assign(new Error('Invalid store price.'),{status:500});const scale=Math.max(0,...normalized.map(value=>(value.split('.')[1]||'').length));let total=0n;for(const value of normalized){const [whole,fraction='']=value.split('.');total+=BigInt(whole+fraction.padEnd(scale,'0'));}if(scale===0)return total.toString();const text=total.toString().padStart(scale+1,'0'),whole=text.slice(0,-scale),fraction=text.slice(-scale).replace(/0+$/,'');return fraction?`${whole}.${fraction}`:whole;}
function decimalToDrops(value){const input=normalizeDecimal(value);if(input===null)throw Object.assign(new Error('Invalid XRP price.'),{status:500});let [whole,fraction='']=input.split('.');if(fraction.length>6)throw Object.assign(new Error('XRP prices may use at most 6 decimal places.'),{status:500});fraction=fraction.padEnd(6,'0');return (BigInt(whole)*1000000n+BigInt(fraction||0)).toString();}
function normalizeCurrency(value){const input=String(value||'').toUpperCase();if(/^[A-F0-9]{40}$/.test(input)){try{return Buffer.from(input,'hex').toString('ascii').replace(/\0+$/g,'')||input;}catch{return input;}}return input;}
function amountMatches(actual,asset,expected){if(asset.type==='native')return typeof actual==='string'&&actual===decimalToDrops(expected);if(!actual||typeof actual!=='object')return false;if(normalizeCurrency(actual.currency)!==normalizeCurrency(asset.currency)||String(actual.issuer||'')!==asset.issuer)return false;return normalizeDecimal(actual.value)===normalizeDecimal(expected);}
function deliveredAmount(tx,meta){const delivered=meta?.delivered_amount??meta?.DeliveredAmount??null;if(delivered&&delivered!=='unavailable')return delivered;if((Number(tx?.Flags||0)&TF_PARTIAL_PAYMENT)!==0)return null;return tx?.DeliverMax??tx?.Amount??null;}
function rpcEndpoints(){return [...new Set([String(process.env.XRPL_RPC_URL||'').trim(),'https://xrplcluster.com/','https://s1.ripple.com:51234/','https://s2.ripple.com:51234/'].filter(Boolean))];}
async function rpc(endpoint,method,params){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},cache:'no-store',body:JSON.stringify({jsonrpc:'2.0',id:'atm-town-attribute-store-v23512',method,params})});const payload=await readJson(response);if(!response.ok)throw new Error(`XRPL request failed (${response.status}).`);const result=payload?.result||{};if(result.status==='error'||result.error)throw new Error(result.error_message||result.error||'XRPL request failed.');return result;}
export async function verifyDestinationTrustline(asset){if(asset.type==='native')return true;let lastError=null;for(const endpoint of rpcEndpoints()){try{const result=await rpc(endpoint,'account_lines',[{account:ATTRIBUTE_STORE_DESTINATION,peer:asset.issuer,ledger_index:'validated',limit:400}]);const ok=Array.isArray(result.lines)&&result.lines.some(line=>normalizeCurrency(line?.currency)===normalizeCurrency(asset.currency)&&String(line?.account||'')===asset.issuer);if(ok)return true;lastError=Object.assign(new Error(`The ATM Town merchant wallet needs a ${asset.label} trust line before accepting ${asset.label}.`),{status:409});}catch(error){lastError=error;}}throw Object.assign(lastError||new Error('Could not verify the merchant trust line.'),{status:lastError?.status||502});}
export async function loadStorePrices(admin,itemIds=null){let query=admin.from('attribute_store_prices').select('item_id,usd_amount,atm_amount,rlusd_amount,xrp_amount,active').eq('active',true);if(itemIds?.length)query=query.in('item_id',itemIds);const {data,error}=await query;if(error)throw error;const prices={};for(const row of data||[])prices[String(row.item_id)]={usd:row.usd_amount===null?null:String(row.usd_amount),atm:row.atm_amount===null?null:String(row.atm_amount),rlusd:row.rlusd_amount===null?null:String(row.rlusd_amount),xrp:row.xrp_amount===null?null:String(row.xrp_amount)};return prices;}
export async function priceCart(admin,itemIds,assetId){const ids=normalizeItemIds(itemIds),asset=storeAsset(assetId),prices=await loadStorePrices(admin,ids);const lineItems=[];for(const id of ids){const row=prices[id];if(!row)throw Object.assign(new Error(`Attribute ${id} is not currently for sale.`),{status:409});const raw=row[asset.id],normalized=normalizeDecimal(raw);if(normalized===null||BigInt(normalized.replace('.',''))<=0n)throw Object.assign(new Error(`${id} does not have a ${asset.label} price yet.`),{status:409});if(asset.type==='native'&&(normalized.split('.')[1]||'').length>6)throw Object.assign(new Error(`${id} XRP price may use at most 6 decimal places.`),{status:500});lineItems.push({item_id:id,amount:normalized});}const totalText=addDecimalStrings(lineItems.map(item=>item.amount));if(totalText==='0')throw Object.assign(new Error('Cart total is invalid.'),{status:500});return {ids,asset,lineItems,total:totalText,prices};}
export function invoiceIdForPurchase(purchaseId){return createHash('sha256').update(`atm-town-attribute-store:${purchaseId}`).digest('hex').toUpperCase();}
export async function createAttributeXamanPayload({purchaseId,invoiceId,asset,total,itemCount}){const amount=asset.type==='native'?decimalToDrops(total):{currency:asset.currency,issuer:asset.issuer,value:String(total)};const response=await fetch(`${XAMAN_API_BASE}/payload`,{method:'POST',headers:xamanHeaders(),cache:'no-store',body:JSON.stringify({txjson:{TransactionType:'Payment',Destination:ATTRIBUTE_STORE_DESTINATION,Amount:amount,InvoiceID:invoiceId},options:{submit:true,expire:ATTRIBUTE_STORE_PAYMENT_WINDOW_MINUTES,force_network:'MAINNET'},custom_meta:{identifier:purchaseId,instruction:`ATM Town Attribute Store: ${itemCount} item${itemCount===1?'':'s'} · ${total} ${asset.label}.`}})});const created=await readJson(response);if(!response.ok||!created?.uuid||!created?.next?.always)throw xamanError(created,'Xaman rejected the Attribute Store payment request');return created;}
export async function cancelAttributePayload(payloadUuid){if(!XAMAN_PAYLOAD_UUID.test(String(payloadUuid||'')))return;try{await fetch(`${XAMAN_API_BASE}/payload/${encodeURIComponent(payloadUuid)}`,{method:'DELETE',headers:xamanHeaders(),cache:'no-store'});}catch{}}
async function fetchTx(txHash){let lastError=null,reached=false;for(const endpoint of rpcEndpoints()){try{const result=await rpc(endpoint,'tx',[{transaction:txHash,binary:false,api_version:2}]);reached=true;if(result?.validated===true)return result;}catch(error){if(/txnNotFound/i.test(String(error?.message||''))){reached=true;continue;}lastError=error;}}if(reached)return null;throw Object.assign(lastError||new Error('All XRPL transaction servers failed.'),{status:502});}
function validateTx(result,txHash,request,asset){if(!result)return {state:'pending'};const tx=result?.tx_json||result?.tx||result?.transaction||(result?.TransactionType?result:{}),meta=result?.meta||result?.metaData||result?.metadata||{};const hash=String(result?.hash||tx?.hash||txHash||'').toUpperCase();if(result.validated!==true)return {state:'pending'};if(hash!==String(txHash).toUpperCase())return {state:'invalid',error:'XRPL transaction hash mismatch.'};if(String(tx.TransactionType||'')!=='Payment')return {state:'invalid',error:'Signed transaction was not a Payment.'};if(String(tx.Destination||'')!==ATTRIBUTE_STORE_DESTINATION)return {state:'invalid',error:'Payment destination did not match ATM Town.'};if(String(tx.Account||'')!==String(request.expected_wallet||''))return {state:'invalid',error:'Payment was signed by a different wallet than the linked ATM Town wallet.'};const resultCode=String(meta?.TransactionResult||meta?.transaction_result||result?.engine_result||'');if(resultCode!=='tesSUCCESS')return {state:'invalid',error:`XRPL payment failed${resultCode?` (${resultCode})`:''}.`};if(String(tx.InvoiceID||'').toUpperCase()!==String(request.invoice_id||'').toUpperCase())return {state:'invalid',error:'Payment invoice did not match this Attribute Store order.'};if(!amountMatches(deliveredAmount(tx,meta),asset,request.total_amount))return {state:'invalid',error:`Delivered ${asset.label} amount did not match the order total.`};return {state:'verified',payment:{hash,payerWallet:String(tx.Account||''),ledgerIndex:result?.ledger_index||tx?.ledger_index||null}};}
export async function resolveAttributePayment(admin,request){const asset=storeAsset(request.asset_id);const lookup=await fetchXamanPayload(request.payload_uuid);if(!lookup.found)return {kind:'failed',error:'Xaman payment request was not found.'};const payload=lookup.payload||{},meta=payload.meta||{};if(!meta.resolved){if(meta.expired===true)return finalizeFailure(admin,request,'expired','The Xaman payment request expired.');const opened=meta.opened_by_deeplink!==null&&meta.opened_by_deeplink!==undefined;return {kind:'pending',phase:opened?'opened':'waiting'};}if(meta.signed!==true)return finalizeFailure(admin,request,'rejected','The Xaman payment request was rejected.');const response=payload.response||{};const nodeType=String(response.dispatched_nodetype||'').toUpperCase();if(nodeType&&!nodeType.includes('MAINNET'))return finalizeFailure(admin,request,'failed','The payment was not submitted to XRPL Mainnet.');if(response.account&&String(response.account)!==String(request.expected_wallet||''))return finalizeFailure(admin,request,'failed','Xaman was signed by a different wallet.');const txHash=String(response.txid||'').toUpperCase();if(!XRPL_TX_HASH.test(txHash))return {kind:'pending',phase:'validating'};const result=await fetchTx(txHash);const verified=validateTx(result,txHash,request,asset);if(verified.state==='pending')return {kind:'pending',phase:'validating'};if(verified.state==='invalid')return finalizeFailure(admin,request,'failed',verified.error);const {data:used,error:usedError}=await admin.from('attribute_purchase_requests').select('id').eq('tx_hash',verified.payment.hash).neq('id',request.id).maybeSingle();if(usedError)throw usedError;if(used)return finalizeFailure(admin,request,'failed','That XRPL transaction has already been used for another purchase.');const now=new Date().toISOString();const {data:paid,error:paidError}=await admin.from('attribute_purchase_requests').update({status:'paid',tx_hash:verified.payment.hash,payer_wallet:verified.payment.payerWallet,ledger_index:verified.payment.ledgerIndex,paid_at:now,completed_at:now,failure_reason:null}).eq('id',request.id).select('*').single();if(paidError)throw paidError;await ensureAttributeEntitlements(admin,paid);return {kind:'paid',request:paid};}
export async function ensureAttributeEntitlements(admin,request){if(!request||request.status!=='paid'||!request.user_id)return;const now=request.paid_at||request.completed_at||new Date().toISOString();const rows=(request.item_ids||[]).map(itemId=>({user_id:request.user_id,item_id:String(itemId),source:'purchase',purchase_id:request.id,tx_hash:request.tx_hash||null,granted_at:now}));if(!rows.length)return;const {error}=await admin.from('attribute_entitlements').upsert(rows,{onConflict:'user_id,item_id'});if(error)throw error;}
async function finalizeFailure(admin,request,status,error){const now=new Date().toISOString();const {data,rowError}=await admin.from('attribute_purchase_requests').update({status,failure_reason:error,completed_at:now}).eq('id',request.id).select('*').single();if(rowError)throw rowError;return {kind:status,request:data,error};}
export function validWallet(value){return XRPL_ADDRESS.test(String(value||''));}
