const client=window.supabase.createClient('https://xnyjurertwohlqczaeux.supabase.co','sb_publishable_MspBOZia1KQFBItNYn6Z-Q_0xASDJzD',{auth:{storageKey:'atm-town-admin-auth'}});
const $=id=>document.getElementById(id);let state=null,payoutId=null;
const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const status=message=>{$('status').textContent=message;};
async function api(action,body){const {data}=await client.auth.getSession();if(!data.session)throw new Error('Sign in required.');const response=await fetch(`/api/leaderboards${body?'':`?action=${action}`}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${data.session.access_token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify({action,...body})}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Request failed.');return result;}
function field(form,label,name,value,type='number'){const host=node('label',label),input=node('input');input.name=name;input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';if(type==='number'){input.min='0';input.step='0.000001';}host.append(input);form.append(host);return input;}
function formRow(title){const row=node('article');row.className='row';row.append(node('h3',title));const form=node('form');form.className='fields';form.style.maxWidth='none';row.append(form);return {row,form};}
async function saveForm(event,action,body){event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await api(action,body);status('Changes saved.');await load();}catch(error){status(error.message);}finally{button.disabled=false;}}
function renderPrices(){const host=$('priceRows');host.replaceChildren();const query=$('search').value.toLowerCase();for(const id of state.item_ids.filter(id=>id.includes(query))){const price=state.prices.find(p=>p.item_id===id)||{active:true,xrp_amount:'3'};const {row,form}=formRow(id.replaceAll(':',' · ').replaceAll('-',' '));for(const [key,label] of [['usd_amount','USD'],['atm_amount','ATM'],['rlusd_amount','RLUSD'],['xrp_amount','XRP']])field(form,label,key,price[key]);field(form,'For sale','active',price.active,'checkbox');const button=node('button','Save price');button.className='save';form.append(button);form.addEventListener('submit',event=>{const data=new FormData(form);saveForm(event,'admin-price',{item_id:id,active:form.elements.active.checked,...Object.fromEntries(['usd_amount','atm_amount','rlusd_amount','xrp_amount'].map(key=>[key,data.get(key)]))});});host.append(row);}}
function renderGames(){const host=$('gameRows');host.replaceChildren();for(const rule of state.rules){const {row,form}=formRow(rule.game_id.replaceAll('-',' ').toUpperCase());field(form,'ATM per coin','atm_per_coin',rule.atm_per_coin);field(form,'Daily ATM per player','daily_atm_limit',rule.daily_atm_limit);const cap=field(form,'Maximum coins per run','max_coins',rule.max_coins);cap.step='1';cap.min='1';cap.max='10000';field(form,'Rewards enabled','enabled',rule.enabled,'checkbox');const button=node('button','Save rewards');button.className='save';form.append(button);form.addEventListener('submit',event=>saveForm(event,'admin-rule',{game_id:rule.game_id,enabled:form.elements.enabled.checked,atm_per_coin:form.elements.atm_per_coin.value,daily_atm_limit:form.elements.daily_atm_limit.value,max_coins:Number(form.elements.max_coins.value)}));host.append(row);}}
function actionButton(host,label,action,id){const button=node('button',label);button.type='button';button.addEventListener('click',async()=>{button.disabled=true;try{const result=await api(action,{id});if(action==='admin-payout'){payoutId=id;$('payment').hidden=false;$('xaman').hidden=!result.deeplink;if(result.deeplink)$('xaman').href=result.deeplink;$('qr').hidden=!result.qr_png;if(result.qr_png)$('qr').src=result.qr_png;status(result.deeplink?'Payment ready for your signature.':'Payment already started; open the existing request in Xaman.');}else if(action==='admin-payout-status')status(result.status==='paid'?'Payment confirmed on the XRPL.':result.error||'Payment awaits ledger confirmation.');else status('Reward updated.');await load();}catch(error){status(error.message);}finally{button.disabled=false;}});host.append(button);}
function renderPayouts(){const host=$('payoutRows');host.replaceChildren();for(const reward of state.rewards){const row=node('article');row.className='row';row.append(node('h3',`${reward.amount||'0'} ATM · ${reward.status.toUpperCase()}`),node('p',`${reward.game_id} · ${reward.coins} coins · ${new Date(reward.started_at).toLocaleString()}`));const wallet=node('p',reward.wallet_address);wallet.className='wallet';row.append(wallet);if(reward.failure_reason)row.append(node('p',reward.failure_reason));if(reward.tx_hash){const link=node('a','View confirmed payment');link.href=`https://livenet.xrpl.org/transactions/${reward.tx_hash}`;link.target='_blank';link.rel='noopener';row.append(link);}const actions=node('div');actions.className='actions';if(reward.status==='review'){actionButton(actions,'Approve','admin-approve',reward.id);actionButton(actions,'Reject','admin-reject',reward.id);}if(reward.status==='approved')actionButton(actions,'Pay in Xaman','admin-payout',reward.id);if(reward.status==='signing')actionButton(actions,'Verify payment','admin-payout-status',reward.id);row.append(actions);host.append(row);}if(!state.rewards.length)host.append(node('p','No reward claims yet.'));}
async function load(){state=await api('admin-state');$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('pending').textContent=state.rewards.filter(r=>r.status==='review').length;$('treasury').textContent=state.treasury||'Not configured';renderPrices();renderGames();renderPayouts();$('auditRows').replaceChildren(...state.audit.map(entry=>{const row=node('article');row.className='row';row.append(node('strong',entry.action),node('p',new Date(entry.created_at).toLocaleString()),node('p',JSON.stringify(entry.details)));return row;}));}
$('loginForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.target,button=form.querySelector('button');button.disabled=true;try{const {error}=await client.auth.signInWithPassword({email:form.elements.email.value,password:form.elements.password.value});if(error)throw error;await load();form.elements.password.value='';status('');}catch(error){status(error.message);}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{await client.auth.signOut();state=null;$('dashboard').hidden=true;$('login').hidden=false;$('logout').hidden=true;status('Signed out.');});
$('refresh').addEventListener('click',()=>load().catch(error=>status(error.message)));$('search').addEventListener('input',renderPrices);
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{for(const other of document.querySelectorAll('[data-tab]')){const active=other===button;other.setAttribute('aria-pressed',String(active));$(other.dataset.tab).hidden=!active;}});
$('verify').addEventListener('click',async()=>{if(!payoutId)return;try{const result=await api('admin-payout-status',{id:payoutId});status(result.status==='paid'?'Payment confirmed on the XRPL.':'Payment awaits ledger confirmation.');await load();}catch(error){status(error.message);}});
load().catch(error=>{if(error.message!=='Sign in required.')status(error.message);});
