import '../js/attribute-effects.js';
const categories={body:'Body',chest:'Chest',face:'Face',head:'Hat / head',backpack:'Backpack',back:'Katana / back accessory',gloves:'Gloves',shoes:'Shoes',aura:'Aura',equipment:'Back equipment'};
const ranges={speed:[.5,2.5,.05],gravity:[.2,3,.05],jump:[.5,4,.05]};
const labels={speed:'Movement speed',gravity:'Gravity',jump:'Jump height'};
const defaults=id=>({speed:id==='shoes:lightning-force-ones'?1.6:1,gravity:1,jump:1});
const el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};
export function mountAttributeEditor({host,client,api,getCatalog,onSaved,status}){
 const details=el('details');details.className='attribute-editor';const summary=el('summary','Add an attribute');details.append(summary);
 const form=el('form');form.className='attribute-editor-form';const grid=el('div');grid.className='fields';form.append(grid);
 const input=(label,name,type='text')=>{const wrap=el('label',label),n=el('input');n.type=type;n.name=name;wrap.append(n);grid.append(wrap);return n;};
 const name=input('Attribute name','name');name.required=true;name.maxLength=70;
 const select=(label,choices)=>{const wrap=el('label',label),n=el('select');for(const [value,text] of choices){const option=el('option',text);option.value=value;n.append(option);}wrap.append(n);grid.append(wrap);return n;};
 const character=select('Character',[]),category=select('Category',Object.entries(categories));
 const file=input('Sprite sheet (transparent PNG)','sprite','file');file.accept='image/png';
 const drop=el('div','Drop a sprite sheet here or choose a file above. 768 × 1280 pixels; 3 columns × 4 rows; down, left, up, right.');drop.className='sprite-drop';form.append(drop);
 const pricing=el('div');pricing.className='fields';const prices={};
 for(const [key,label] of [['xrp_amount','XRP price'],['atm_amount','ATM price'],['rlusd_amount','RLUSD price'],['usd_amount','USD price']]){const wrap=el('label',label),n=el('input');n.type='number';n.min='0.000001';n.step='0.000001';wrap.append(n);pricing.append(wrap);prices[key]=n;}
 const saleLabel=el('label','For sale'),sale=el('input');sale.type='checkbox';saleLabel.append(sale);pricing.append(saleLabel);form.append(pricing);
 const effects=el('fieldset'),legend=el('legend','Movement effects');effects.append(legend);const sliders={};
 for(const [key,[min,max,step]] of Object.entries(ranges)){const wrap=el('label',labels[key]),range=el('input'),output=el('output');range.type='range';range.min=min;range.max=max;range.step=step;range.value='1';range.setAttribute('aria-label',labels[key]);const update=()=>{output.value=`${Number(range.value).toFixed(2)}×`;};range.addEventListener('input',update);wrap.append(range,output);effects.append(wrap);sliders[key]=range;update();}
 const reset=el('button','Reset movement');reset.type='button';reset.addEventListener('click',()=>setEffects(defaults(editId)));effects.append(reset,el('p','1× is normal. Equipped attributes multiply together, with limits of 3× speed, 8× jump height and 0.1–3× gravity. The stronger of equipped speed and Lightning applies. Astronaut and Bounce retain their base jump effects.'));form.append(effects);
 const preview=el('section');preview.className='sprite-preview';preview.append(el('h3','Try it before publishing'));
 const direction=el('select');direction.setAttribute('aria-label','Preview direction');for(const value of ['down','left','up','right']){const option=el('option',value);option.value=value;direction.append(option);}
 const canvas=el('canvas');canvas.width=720;canvas.height=360;canvas.tabIndex=0;canvas.setAttribute('aria-label','Movement preview. Arrow keys move, Space jumps.');preview.append(direction,canvas);
 const controls=el('div');controls.className='preview-controls';const held=new Set();let jumping=false,jumpElapsed=0,x=360,y=250;const readEffects=()=>Object.fromEntries(Object.entries(sliders).map(([key,n])=>[key,Number(n.value)]));
 function jump(){if(!jumping){jumping=true;jumpElapsed=0;}}
 for(const [key,label] of [['left','←'],['up','↑'],['down','↓'],['right','→'],['jump','Jump']]){const button=el('button',label);button.type='button';button.setAttribute('aria-label',key==='jump'?'Jump':`Move ${key}`);button.addEventListener('pointerdown',event=>{event.preventDefault();button.setPointerCapture(event.pointerId);if(key==='jump')jump();else held.add(key);});for(const type of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(type,()=>held.delete(key));controls.append(button);}
 canvas.addEventListener('keydown',event=>{const key=({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'})[event.key];if(key){held.add(key);event.preventDefault();}if(event.code==='Space'){event.preventDefault();jump();}});canvas.addEventListener('keyup',event=>{held.delete(({ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down'})[event.key]);});canvas.addEventListener('blur',()=>held.clear());window.addEventListener('blur',()=>held.clear());
 preview.append(controls,el('p','Use the arrows and Jump, or focus the preview and use your keyboard.'));form.append(preview);
 const message=el('p');message.setAttribute('role','status');form.append(message);const actions=el('div');actions.className='editor-actions';const publish=el('button','Publish attribute'),cancel=el('button','New attribute');cancel.type='button';actions.append(publish,cancel);form.append(actions);details.append(form);host.append(details);
 let editId=null,sprite=null,previewSprite=null,base=null,objectUrl=null,checkedFile=null,selectionMade=false,uploadPath=null,generation=0,busy=false;
 const setEffects=value=>{for(const [key,n] of Object.entries(sliders)){n.value=String(value?.[key]??1);n.dispatchEvent(new Event('input'));}};
 const loadBase=()=>{base=new Image();base.src='/'+(getCatalog().characters.find(item=>item.id===character.value)?.sprite_src||`assets/characters/playable/${character.value==='classic'?'atm':character.value}.webp`);};character.addEventListener('change',loadBase);
 function characters(){const previous=character.value;character.replaceChildren(...getCatalog().characters.map(item=>{const option=el('option',item.name);option.value=item.id;return option;}));if(getCatalog().characters.some(item=>item.id===previous))character.value=previous;}
 async function validateFile(candidate){selectionMade=!!candidate;const ticket=++generation;uploadPath=null;checkedFile=null;previewSprite=null;if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=null;
  if(!candidate)return;try{if(candidate.size>6*1024*1024||candidate.type!=='image/png')throw Error('Choose a PNG file up to 6 MB.');const image=new Image(),url=URL.createObjectURL(candidate);objectUrl=url;await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('This image could not be read.'));image.src=url;});if(ticket!==generation)return;if(image.naturalWidth!==768||image.naturalHeight!==1280)throw Error('Use a 768 × 1280 sprite sheet.');const check=el('canvas');check.width=768;check.height=1280;const ctx=check.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,768,1280).data;let transparent=false;for(let i=3;i<pixels.length;i+=4){if(pixels[i]<255){transparent=true;break;}}if(!transparent)throw Error('The background must be transparent.');previewSprite=image;checkedFile=candidate;message.textContent='Sheet ready. Check all four directions and movement before publishing.';}catch(error){if(ticket===generation)message.textContent=error.message;}
 }
 file.addEventListener('change',()=>validateFile(file.files[0]));drop.addEventListener('dragover',event=>{event.preventDefault();drop.classList.add('dragging');});drop.addEventListener('dragleave',()=>drop.classList.remove('dragging'));drop.addEventListener('drop',event=>{event.preventDefault();drop.classList.remove('dragging');validateFile(event.dataTransfer.files[0]);});
 function open(item=null,price={}){if(busy)return;generation++;editId=item?.id||null;sprite=item?.sprite_path||null;uploadPath=null;checkedFile=null;selectionMade=false;previewSprite=null;file.value='';characters();character.value=item?.characterIds?.[0]||'classic';category.value=item?.category||item?.id?.split(':')[0]||'shoes';if(!categories[category.value])category.value='shoes';character.disabled=category.disabled=!!item;name.value=item?.name||'';for(const [key,n] of Object.entries(prices))n.value=Object.hasOwn(price,key)?(price[key]??''):(key==='xrp_amount'?'3':'');sale.checked=price.active!==false;setEffects(item?.effects||defaults(editId));summary.textContent=item?`Edit ${item.name}`:'Add an attribute';publish.textContent=item?'Save changes':'Publish attribute';message.textContent=item?'Saved changes apply to equipped items when the game refreshes.':'Choose a character, category and sprite sheet.';loadBase();if(sprite){const image=new Image();image.crossOrigin='anonymous';image.src=client.storage.from('attribute-sprites').getPublicUrl(sprite).data.publicUrl;previewSprite=image;}else if(item){const image=new Image();image.src=item.sprite_src||'';previewSprite=image;}details.open=true;details.scrollIntoView({behavior:'smooth',block:'start'});}
 cancel.addEventListener('click',()=>open());
 form.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;if(!editId&&!checkedFile){message.textContent='Choose a valid sprite sheet first.';return;}if(selectionMade&&!checkedFile){message.textContent='Wait for the selected sprite sheet to pass validation.';return;}busy=true;publish.disabled=true;file.disabled=true;cancel.disabled=true;try{if(checkedFile&&!uploadPath){message.textContent='Uploading sprite sheet…';const upload=await api('admin-attribute-upload',{});const result=await client.storage.from(upload.bucket).uploadToSignedUrl(upload.path,upload.token,checkedFile,{contentType:'image/png',cacheControl:'31536000'});if(result.error)throw result.error;uploadPath=upload.path;}message.textContent='Saving attribute…';const saved=await api('admin-attribute-save',{item_id:editId,name:name.value,character_id:character.value,category:category.value,sprite_path:uploadPath,effects:readEffects(),active:sale.checked,...Object.fromEntries(Object.entries(prices).map(([key,n])=>[key,n.value]))});editId=saved.item_id||editId;sprite=uploadPath||sprite;checkedFile=null;selectionMade=false;uploadPath=null;file.value='';character.disabled=category.disabled=!!editId;summary.textContent=`Edit ${name.value}`;publish.textContent='Save changes';await onSaved();message.textContent='Saved. Available in the game after its next catalog refresh (within one minute).';status('Attribute and movement effects saved.');details.open=false;}catch(error){message.textContent=error.message;status(error.message);}finally{busy=false;publish.disabled=false;file.disabled=false;cancel.disabled=false;}});
 let previous=0,elapsed=0;const ctx=canvas.getContext('2d');
 function draw(timestamp){const dt=Math.min(.05,(timestamp-previous)/1000||0);previous=timestamp;elapsed+=dt;if(details.open&&!document.hidden){const values=globalThis.ATMAttributeEffects.combine([readEffects()]);const astronaut=editId==='body:astronaut';const profile=globalThis.ATMAttributeEffects.jumpProfile(values,38*(astronaut?4:1),.64*(astronaut?2.7:1));let dx=(held.has('right')?1:0)-(held.has('left')?1:0),dy=(held.has('down')?1:0)-(held.has('up')?1:0),length=Math.hypot(dx,dy);if(length){dx/=length;dy/=length;x=Math.max(70,Math.min(650,x+dx*182*values.speed*dt));y=Math.max(165,Math.min(325,y+dy*182*values.speed*dt));direction.value=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';}if(jumping){jumpElapsed+=dt;if(jumpElapsed>=profile.duration)jumping=false;}const lift=jumping?Math.sin(Math.PI*jumpElapsed/profile.duration)*profile.height:0;ctx.clearRect(0,0,720,360);ctx.fillStyle='#101a2d';ctx.fillRect(0,0,720,360);ctx.strokeStyle='#213a51';for(let gy=170;gy<360;gy+=30){ctx.beginPath();ctx.moveTo(0,gy);ctx.lineTo(720,gy);ctx.stroke();}ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(x,y,25,7,0,0,Math.PI*2);ctx.fill();const sequence=[0,1,2,1],frame=length?sequence[Math.floor(elapsed/.14)%4]:1,row=['down','left','up','right'].indexOf(direction.value);const layer=image=>{if(image?.complete&&image.naturalWidth===768&&image.naturalHeight===1280)ctx.drawImage(image,frame*256,row*320,256,320,x-128*.33,y-303*.33-lift,256*.33,320*.33);};if(category.value!=='body'||!previewSprite?.complete)layer(base);layer(previewSprite);ctx.fillStyle='#b9dde8';ctx.font='14px sans-serif';ctx.fillText(`Speed ${values.speed.toFixed(2)}×   Gravity ${values.gravity.toFixed(2)}×   Jump ${values.jump.toFixed(2)}×`,18,24);}requestAnimationFrame(draw);}
 setEffects(defaults());prices.xrp_amount.value='3';sale.checked=true;category.value='shoes';details.addEventListener('toggle',()=>{if(details.open&&!editId){characters();loadBase();}});requestAnimationFrame(draw);return {open,refresh:characters};
}
