import {footprintPoints,validateFootprint} from '../js/footprint-geometry.js';
export function mountObjectEditor({host,client,api,node,status}){
 let rows=[],draft=null,image=null,file=null,path=null,url=null,busy=false,bounds=null,mapImage=null,initialized=false,raf=null;
 const camera={x:0,y:0,scale:.1};const pointers=new Map();let drag=null;let generation=0,points=[],drawing=false;let zone="collision",zones={},depthLine=0,actionSettings={type:"message",destination:"hq",text:""};
 const controls=node('div');controls.className='object-controls';const chooser=node('select');chooser.setAttribute('aria-label','Saved map objects');const fresh=node('button','New object');fresh.type='button';controls.append(chooser,fresh);host.append(controls);
 const form=node('form');form.className='object-fields';const fields={};
 function field(title,key,type,value){const label=node('label',title),input=node('input');input.type=type;input.value=value??'';if(type==='checkbox')input.checked=value;label.append(input);form.append(label);fields[key]=input;return input;}
 field('Object name','name','text','NFT Donation Box').maxLength=70;
 const upload=field('PNG · transparency optional · up to 6 MB / 2048 × 2048','file','file');upload.accept='image/png';
 const width=field('Width in world pixels','width','number',100);width.min=16;width.max=1000;
 field('X position','x','number',0).step='any';field('Y position (base)','y','number',0).step='any';
 field('Visible in town','active','checkbox',true);field('Solid base (blocks walking)','solid','checkbox',false);
 const collisionLabel=node('label','Blocked footprint shape'),shape=node('select');for(const [value,title] of [['rectangle','Rectangle'],['polygon','Custom polygon']]){const option=node('option',title);option.value=value;shape.append(option);}collisionLabel.append(shape);form.append(collisionLabel);
 const cw=field('Blocked width','collisionWidth','number',80),cd=field('Blocked length','collisionDepth','number',22),cx=field('Footprint offset X','collisionX','number',0),cy=field('Footprint offset Y','collisionY','number',-7);for(const f of [cw,cd]){f.min=1;f.max=2048;f.step='any';}for(const f of [cx,cy]){f.min=-2048;f.max=2048;f.step='any';}
 const zoneLabel=node('label','Edit area'),zoneSelect=node('select');for(const [value,title] of [['collision','Blocked area'],['depth','Depth mask'],['stairs','Stairs walkway'],['action','Action area']]){const option=node('option',title);option.value=value;zoneSelect.append(option);}zoneLabel.append(zoneSelect);form.append(zoneLabel);
 const depthInput=field('Depth line offset Y (players behind this line are covered)','depthLine','number',0);depthInput.step='any';
 const actionLabel=node('label','Action'),actionSelect=node('select');for(const [value,title] of [['message','Show message'],['enter','Enter building'],['vending','Use vending machine'],['events','Open event controls']]){const option=node('option',title);option.value=value;actionSelect.append(option);}actionLabel.append(actionSelect);form.append(actionLabel);
 const destinationLabel=node('label','Interior'),destination=node('select');for(const value of ['hq','gallery','arcade','lounge']){const option=node('option',value.toUpperCase());option.value=value;destination.append(option);}destinationLabel.append(destination);form.append(destinationLabel);
 const actionText=field('Message','actionText','text','');actionText.maxLength=500;
 const clearZone=node('button','Remove this area');clearZone.type='button';form.append(clearZone);
 function rememberZone(){zones[zone]=shape.value==='polygon'&&points.length<3?null:collision();depthLine=Number(depthInput.value);actionSettings={type:actionSelect.value,destination:destination.value,text:actionText.value};}
 function loadZone(){const c=zones[zone]||{type:'rectangle',width:Number(width.value)*.8,depth:22,offsetX:0,offsetY:-7};shape.value=c.type;points=c.type==='polygon'?c.points.map(p=>({...p})):[];if(points.length)syncPolygonFields();else{cw.value=c.width;cd.value=c.depth;cx.value=c.offsetX;cy.value=c.offsetY;}drawing=false;depthInput.closest('label').hidden=zone!=='depth';for(const label of [actionLabel,destinationLabel,actionText.closest('label')])label.hidden=zone!=='action';cornerList();maskStatus();}
 zoneSelect.onchange=()=>{rememberZone();zone=zoneSelect.value;loadZone();};clearZone.onclick=()=>{zones[zone]=null;shape.value='polygon';points=[];drawing=false;cornerList();maskStatus();};
 function allCollision(){rememberZone();if(!zones.collision)fields.solid.checked=false;const base=zones.collision||{type:'rectangle',width:Number(width.value)*.8,depth:22,offsetX:0,offsetY:-7};return {...base,masks:Object.fromEntries(['depth','stairs','action'].filter(k=>zones[k]).map(k=>[k,zones[k]])),depthLine,action:actionSettings};}
 const save=node('button','Save object');const remove=node('button','Remove object');remove.type='button';remove.disabled=true;form.append(save,remove);host.append(form);
 const tools=node('div');tools.className='object-controls';const fit=node('button','Fit town'),plus=node('button','Zoom +'),minus=node('button','Zoom −'),center=node('button','Move object to view center');for(const b of [fit,plus,minus,center])b.type='button';tools.append(fit,plus,minus,center);host.append(tools);
 const maskTools=node('div');maskTools.className='object-controls';const drawMask=node('button','Draw new footprint'),finishMask=node('button','Finish polygon'),undoMask=node('button','Undo last corner'),octagon=node('button','Octagon'),maskInfo=node('p');maskInfo.setAttribute('aria-live','polite');for(const b of [drawMask,finishMask,undoMask,octagon])b.type='button';maskTools.append(drawMask,finishMask,undoMask,octagon);host.append(maskTools,maskInfo);
 const corners=node('div');corners.className='footprint-corners';host.append(corners);
 function collision(){return shape.value==='polygon'?{type:'polygon',points:points.map(p=>({...p}))}:{type:'rectangle',width:Number(cw.value),depth:Number(cd.value),offsetX:Number(cx.value),offsetY:Number(cy.value)};}
 function syncPolygonFields(){if(!points.length)return;const xs=points.map(p=>p.x),ys=points.map(p=>p.y),left=Math.min(...xs),right=Math.max(...xs),top=Math.min(...ys),bottom=Math.max(...ys);cw.value=+(right-left).toFixed(2);cd.value=+(bottom-top).toFixed(2);cx.value=+((left+right)/2).toFixed(2);cy.value=+((top+bottom)/2).toFixed(2);}
 function cornerList(){corners.replaceChildren();if(shape.value!=='polygon')return;points.forEach((point,i)=>{const row=node('div'),label=node('span',`Corner ${i+1}`);row.className='footprint-corner';row.append(label);for(const key of ['x','y']){const input=node('input');input.type='number';input.step='any';input.value=point[key];input.setAttribute('aria-label',`Corner ${i+1} offset ${key.toUpperCase()}`);input.onchange=()=>{points[i][key]=Number(input.value);syncPolygonFields();maskStatus();};row.append(input);}const remove=node('button','Remove');remove.type='button';remove.onclick=()=>{points.splice(i,1);syncPolygonFields();cornerList();maskStatus();};row.append(remove);corners.append(row);});}
 function maskStatus(){const polygon=shape.value==='polygon';maskTools.hidden=!polygon;corners.hidden=!polygon;drawMask.setAttribute('aria-pressed',String(drawing));finishMask.disabled=busy||!drawing||points.length<3;undoMask.disabled=busy||!points.length;let error='';try{validateFootprint(collision());}catch(e){error=e.message;}maskInfo.textContent=zone!=='collision'?(drawing?'Tap corners on the map, then Finish polygon.':zone==='stairs'?'Stairs make this area walkable across blocked terrain.':zone==='depth'?'Blue area covers players behind the depth line.':'Players in this area can press ACTION.') : !fields.solid.checked?'Walking is not blocked. Enable Solid base to use this footprint.':error|| (drawing?`${points.length} corners. Tap the map to add corners, then Finish polygon.`:polygon?`${points.length} corners. Drag numbered corners, or edit their offsets below.`:'Red shows the area that blocks walking. Adjust its width, length and offsets.');}
 shape.onchange=()=>{drawing=false;if(shape.value==='polygon')points=footprintPoints({width:Number(width.value),collision:{type:'rectangle',width:Number(cw.value),depth:Number(cd.value),offsetX:Number(cx.value),offsetY:Number(cy.value)}});cornerList();maskStatus();};
 for(const f of [cw,cd,cx,cy]){f.addEventListener('input',()=>{if(shape.value==='polygon'&&points.length){const xs=points.map(p=>p.x),ys=points.map(p=>p.y),w=Math.max(...xs)-Math.min(...xs),d=Math.max(...ys)-Math.min(...ys),x=(Math.max(...xs)+Math.min(...xs))/2,y=(Math.max(...ys)+Math.min(...ys))/2,nw=Number(cw.value),nd=Number(cd.value),nx=Number(cx.value),ny=Number(cy.value);if(nw>0&&nd>0&&[nx,ny].every(Number.isFinite)){points=points.map(p=>({x:nx+(p.x-x)*nw/Math.max(w,.01),y:ny+(p.y-y)*nd/Math.max(d,.01)}));cornerList();}}maskStatus();});}
 fields.solid.onchange=maskStatus;
 drawMask.onclick=()=>{shape.value='polygon';points=[];drawing=true;if(zone==='collision')fields.solid.checked=true;cornerList();maskStatus();};
 finishMask.onclick=()=>{try{validateFootprint(collision());drawing=false;maskStatus();}catch(e){message(e.message);}};
 undoMask.onclick=()=>{points.pop();syncPolygonFields();cornerList();maskStatus();};
 octagon.onclick=()=>{shape.value='polygon';drawing=false;const x=Number(cx.value),y=Number(cy.value),w=Number(cw.value)/2,d=Number(cd.value)/2;points=[[-.5,-1],[.5,-1],[1,-.5],[1,.5],[.5,1],[-.5,1],[-1,.5],[-1,-.5]].map(([a,b])=>({x:x+a*w,y:y+b*d}));if(zone==='collision')fields.solid.checked=true;cornerList();maskStatus();};

 const canvas=node('canvas');canvas.className='object-map';canvas.setAttribute('aria-label','Town map. Drag an object to place it; drag empty space to pan. Position fields provide keyboard placement.');host.append(canvas);
 const note=node('p','Drag the image to place it. Drag empty space to pan; use zoom buttons, wheel or two fingers to zoom. X/Y fields allow exact placement.');host.append(note);
 const context=canvas.getContext('2d');
 function message(text){note.textContent=text;}
 function cleanup(){if(url)URL.revokeObjectURL(url);url=null;}
 function coords(){return {x:Number(fields.x.value),y:Number(fields.y.value),width:Number(width.value)};}
 function visibleDraft(){return image?{...draft,...coords(),image_width:image.naturalWidth,image_height:image.naturalHeight,collision:collision(),solid:fields.solid.checked}:null;}
 function screenToWorld(x,y){return {x:camera.x+x/camera.scale,y:camera.y+y/camera.scale};}
 function setPosition(x,y){if(!bounds)return;fields.x.value=Math.round(Math.max(bounds.minX,Math.min(bounds.maxX,x))*10)/10;fields.y.value=Math.round(Math.max(bounds.minY,Math.min(bounds.maxY,y))*10)/10;}
 function reset(row=null){generation++;cleanup();file=null;path=null;image=null;draft=row?{...row}:null;upload.value='';fields.name.value=row?.name||'NFT Donation Box';width.value=row?.width||100;fields.active.checked=row?.active??true;fields.solid.checked=row?.solid??false;zones={collision:row?.collision||null,...row?.collision?.masks};zone='collision';zoneSelect.value=zone;depthLine=row?.collision?.depthLine||0;depthInput.value=depthLine;actionSettings=row?.collision?.action||{type:'message',destination:'hq',text:''};actionSelect.value=actionSettings.type;destination.value=actionSettings.destination;actionText.value=actionSettings.text;const c=row?.collision||{type:'rectangle',width:Number(width.value)*.8,depth:22,offsetX:0,offsetY:-7};shape.value=c.type==='polygon'?'polygon':'rectangle';drawing=false;points=c.type==='polygon'?c.points.map(p=>({...p})):[];if(c.type==='polygon')syncPolygonFields();else{cw.value=c.width;cd.value=c.depth;cx.value=c.offsetX;cy.value=c.offsetY;}loadZone();setPosition(row?.x??camera.x+canvas.clientWidth/camera.scale/2,row?.y??camera.y+canvas.clientHeight/camera.scale/2);remove.disabled=!row;chooser.value=row?.id||'';if(row){const ticket=generation;const img=new Image();img.onload=()=>{if(ticket===generation)image=img;};img.src=row.sprite_url;}message(row?'Drag to reposition, then save.':'Upload a PNG to preview a new map object.');}
 async function reload(id){const result=await api('admin-objects');rows=result.objects;chooser.replaceChildren(node('option','New object'));chooser.firstChild.value='';for(const row of rows){const opt=node('option',row.name+(row.active?'':' (hidden)'));opt.value=row.id;chooser.append(opt);}if(id)reset(rows.find(o=>o.id===id));}
 function fitMap(){if(!bounds||!canvas.clientWidth)return;camera.scale=Math.min(canvas.clientWidth/bounds.width,canvas.clientHeight/bounds.height)*.92;camera.x=bounds.minX-(canvas.clientWidth/camera.scale-bounds.width)/2;camera.y=bounds.minY-(canvas.clientHeight/camera.scale-bounds.height)/2;}
 function zoom(factor,sx=canvas.clientWidth/2,sy=canvas.clientHeight/2){const p=screenToWorld(sx,sy);camera.scale=Math.max(.035,Math.min(2,camera.scale*factor));camera.x=p.x-sx/camera.scale;camera.y=p.y-sy/camera.scale;}
 function position(e){const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 function draw(){raf=null;if(host.closest('[hidden]')||document.hidden)return;const w=canvas.clientWidth,h=canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}context.setTransform(dpr,0,0,dpr,0,0);context.fillStyle='#071820';context.fillRect(0,0,w,h);context.save();context.scale(camera.scale,camera.scale);context.translate(-camera.x,-camera.y);if(mapImage?.complete&&mapImage.naturalWidth&&bounds)context.drawImage(mapImage,bounds.minX,bounds.minY,bounds.width,bounds.height);
 const selected=visibleDraft();for(const o of rows){if(o.id===draft?.id||!o.active)continue;let img=o._image;if(!img){img=new Image();img.src=o.sprite_url;o._image=img;}paint(img,o,false);}if(selected)paint(image,selected,true);context.restore();raf=requestAnimationFrame(draw);}
 function paint(img,o,selected){if(!img?.complete||!img.naturalWidth)return;const h=o.width*img.naturalHeight/img.naturalWidth;context.globalAlpha=(selected&&!fields.active.checked)?0.5:1;context.drawImage(img,o.x-o.width/2,o.y-h,o.width,h);context.globalAlpha=1;if(o.solid||selected){const vertices=footprintPoints(o);if(vertices.length){context.beginPath();vertices.forEach((p,i)=>context[i?'lineTo':'moveTo'](o.x+p.x,o.y+p.y));context.closePath();context.fillStyle=selected?({collision:'#ff596655',depth:'#459bff66',stairs:'#55ee8866',action:'#ffcc4466'}[zone]):'#ff59662a';context.fill();context.strokeStyle='#ff7a86';context.lineWidth=2/camera.scale;context.stroke();if(selected&&shape.value==='polygon'){vertices.forEach((p,i)=>{context.beginPath();context.arc(o.x+p.x,o.y+p.y,8/camera.scale,0,Math.PI*2);context.fillStyle='#ffe1aa';context.fill();context.fillStyle='#182136';context.font=`bold ${11/camera.scale}px system-ui`;context.textAlign='center';context.textBaseline='middle';context.fillText(String(i+1),o.x+p.x,o.y+p.y);});}}}if(selected){context.strokeStyle='#58f1e6';context.lineWidth=2/camera.scale;context.strokeRect(o.x-o.width/2,o.y-h,o.width,h);context.beginPath();context.arc(o.x,o.y,5/camera.scale,0,Math.PI*2);context.fillStyle='#ffd166';context.fill();}}
 function startDraw(){if(!raf)raf=requestAnimationFrame(draw);}
 canvas.addEventListener('pointerdown',e=>{if(busy)return;canvas.setPointerCapture(e.pointerId);const p=position(e);pointers.set(e.pointerId,p);if(pointers.size===1){const world=screenToWorld(p.x,p.y),o=visibleDraft(),h=o?o.width*image.naturalHeight/image.naturalWidth:0;const hit=o&&world.x>=o.x-o.width/2&&world.x<=o.x+o.width/2&&world.y>=o.y-h&&world.y<=o.y+10;const corner=!drawing&&o&&shape.value==='polygon'?points.findIndex(v=>Math.hypot((o.x+v.x-world.x)*camera.scale,(o.y+v.y-world.y)*camera.scale)<=14):-1;drag={kind:corner>=0?'corner':drawing&&o?'add':hit?'object':'pan',corner,p,start:p,world,anchor:o};}else drag=null;});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;const prev=[...pointers.values()],p=position(e);pointers.set(e.pointerId,p);if(pointers.size===2){const now=[...pointers.values()],distance=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);const d=distance(prev);if(d>2)zoom(distance(now)/d,(now[0].x+now[1].x)/2,(now[0].y+now[1].y)/2);return;}if(!drag)return;if(drag.kind==='corner'){const point=screenToWorld(p.x,p.y);points[drag.corner]={x:+(point.x-drag.anchor.x).toFixed(2),y:+(point.y-drag.anchor.y).toFixed(2)};syncPolygonFields();maskStatus();}else if(drag.kind==='add'){if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>6){drag.kind='pan';}}else if(drag.kind==='object'){const point=screenToWorld(p.x,p.y);setPosition(drag.anchor.x+point.x-drag.world.x,drag.anchor.y+point.y-drag.world.y);}else{camera.x-=(p.x-drag.p.x)/camera.scale;camera.y-=(p.y-drag.p.y)/camera.scale;drag.p=p;}});
 const end=e=>{if(e.type==='pointerup'&&drag?.kind==='add'&&pointers.size===1){if(points.length>=32)message('A footprint supports up to 32 corners.');else{const p=screenToWorld(position(e).x,position(e).y);points.push({x:+(p.x-drag.anchor.x).toFixed(2),y:+(p.y-drag.anchor.y).toFixed(2)});syncPolygonFields();}}pointers.delete(e.pointerId);drag=null;cornerList();maskStatus();};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('wheel',e=>{e.preventDefault();const p=position(e);zoom(Math.exp(-e.deltaY*.001),p.x,p.y);},{passive:false});
 fit.onclick=fitMap;plus.onclick=()=>zoom(1.3);minus.onclick=()=>zoom(1/1.3);center.onclick=()=>setPosition(camera.x+canvas.clientWidth/camera.scale/2,camera.y+canvas.clientHeight/camera.scale/2);fresh.onclick=()=>reset();chooser.onchange=()=>reset(rows.find(o=>o.id===chooser.value));
 upload.onchange=async()=>{const ticket=++generation;cleanup();file=null;path=null;image=null;const candidate=upload.files[0];if(!candidate)return;try{if(candidate.size>6291456)throw Error('PNG must be at most 6 MB.');const bytes=new Uint8Array(await candidate.slice(0,24).arrayBuffer());if(bytes.length<24||bytes.slice(0,8).join(',')!=='137,80,78,71,13,10,26,10')throw Error('Choose a PNG image.');const view=new DataView(bytes.buffer);if(view.getUint32(16)>2048||view.getUint32(20)>2048)throw Error('PNG dimensions must be at most 2048 × 2048.');const local=URL.createObjectURL(candidate);const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('This PNG could not be decoded.'));i.src=local;});if(ticket!==generation){URL.revokeObjectURL(local);return;}url=local;image=img;file=candidate;message('Drag the image to its position, adjust width, then save.');}catch(error){if(ticket===generation)message(error.message);}};
 function lock(value){busy=value;for(const element of [...form.elements,...corners.querySelectorAll('input,button'),shape,chooser,fresh,center,drawMask,octagon,undoMask,finishMask])element.disabled=value;remove.disabled=value||!draft?.id;if(!value)maskStatus();}
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;if(!image){message('Upload a valid PNG first.');return;}let footprint;try{footprint=validateFootprint(allCollision());}catch(error){message(error.message);return;}lock(true);try{if(file&&!path){message('Uploading PNG…');const upload=await api('admin-object-upload',{});const result=await client.storage.from(upload.bucket).uploadToSignedUrl(upload.path,upload.token,file,{contentType:'image/png',cacheControl:'31536000'});if(result.error)throw result.error;path=upload.path;}message('Saving placement…');const result=await api('admin-object-save',{id:draft?.id,name:fields.name.value,...coords(),sprite_path:path,active:fields.active.checked,solid:fields.solid.checked,collision:footprint});await reload(result.object.id);message('Saved. Players see this placement within one minute.');status('Map object saved.');}catch(error){message(error.message);}finally{lock(false);}};
 remove.onclick=async()=>{if(busy||!draft?.id)return;lock(true);try{await api('admin-object-delete',{id:draft.id});await reload();reset();message('Object removed from the town.');}catch(error){message(error.message);}finally{lock(false);}};
 return {async open(){try{if(!initialized){const response=await fetch('/assets/world/manifest.json',{cache:'no-store'});if(!response.ok)throw Error('Town map unavailable');bounds=(await response.json()).bounds;mapImage=new Image();mapImage.src='/assets/world/overview/day.webp';await reload();fitMap();reset();initialized=true;}else await reload();startDraw();}catch(error){message(error.message);}},};
}
