import { readdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const ignoredDirectories = new Set(['.git', 'node_modules']);
const runtimeSourceExtensions = new Set(['.html', '.js', '.json']);
const maskPattern = /(blocked|collision|depth|interaction|stairs?|mask)/i;

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (ignoredDirectories.has(entry.name)) continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(fullPath));
    else files.push(fullPath);
  }
  return files;
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 ** 2) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 ** 2).toFixed(2)} MB`;
}

const files = await walk(root);
const relativeFiles = files.map((file) => path.relative(root, file).replaceAll(path.sep, '/'));
const sourceFiles = files.filter((file) => runtimeSourceExtensions.has(path.extname(file).toLowerCase()));
const sourceText = (await Promise.all(sourceFiles.map(async (file) => {
  try { return await readFile(file, 'utf8'); } catch { return ''; }
}))).join('\n');

const records = [];
for (let index = 0; index < files.length; index += 1) {
  const file = files[index];
  const relative = relativeFiles[index];
  const extension = path.extname(file).toLowerCase();
  const info = await stat(file);
  const baseName = path.basename(file);
  const isPng = extension === '.png';
  const isMask = isPng && maskPattern.test(baseName);
  const referenced = sourceText.includes(baseName);
  const webpCandidate = isPng && !isMask;
  records.push({ relative, extension: extension || '[none]', bytes: info.size, referenced, isMask, webpCandidate });
}

const pngRecords = records.filter((record) => record.extension === '.png');
const candidates = pngRecords.filter((record) => record.webpCandidate).sort((a, b) => b.bytes - a.bytes);
const masks = pngRecords.filter((record) => record.isMask).sort((a, b) => b.bytes - a.bytes);
const unreferenced = records.filter((record) => ['.png', '.webp', '.wav', '.mp3'].includes(record.extension) && !record.referenced).sort((a, b) => b.bytes - a.bytes);
const totalBytes = records.reduce((sum, record) => sum + record.bytes, 0);
const pngBytes = pngRecords.reduce((sum, record) => sum + record.bytes, 0);
const candidateBytes = candidates.reduce((sum, record) => sum + record.bytes, 0);

const lines = [
  '# ATM Town Asset Audit',
  '',
  'Generated by `npm run audit:assets`.',
  '',
  '## Summary',
  '',
  `- Repository files: **${records.length}**`,
  `- Repository size: **${formatBytes(totalBytes)}**`,
  `- PNG files: **${pngRecords.length}** totaling **${formatBytes(pngBytes)}**`,
  `- Safe-review PNG → transparent WebP candidates: **${candidates.length}** totaling **${formatBytes(candidateBytes)}**`,
  `- PNG masks retained for exact pixel-color behavior: **${masks.length}**`,
  '',
  '> “Candidate” means the filename does not look like a collision, depth, stair, blocked, or interaction mask. Each conversion must still be visually checked before the PNG is removed.',
  '',
  '## Largest WebP Candidates',
  '',
  '| Asset | Size | Runtime reference found |',
  '|---|---:|:---:|',
  ...candidates.slice(0, 40).map((record) => `| \`${record.relative}\` | ${formatBytes(record.bytes)} | ${record.referenced ? 'Yes' : 'No'} |`),
  '',
  '## Exact-Color PNG Masks',
  '',
  '| Asset | Size |',
  '|---|---:|',
  ...masks.map((record) => `| \`${record.relative}\` | ${formatBytes(record.bytes)} |`),
  '',
  '## Assets With No Filename Reference Found',
  '',
  'This is a review list, not permission to delete. Assets can be loaded dynamically or retained as source material.',
  '',
  '| Asset | Size |',
  '|---|---:|',
  ...unreferenced.slice(0, 60).map((record) => `| \`${record.relative}\` | ${formatBytes(record.bytes)} |`),
  ''
];

const outputPath = path.join(root, 'docs', 'ASSET-AUDIT.md');
await writeFile(outputPath, lines.join('\n'));
console.log(`Wrote ${path.relative(root, outputPath)} with ${candidates.length} WebP candidates and ${masks.length} protected masks.`);
